import {chromium} from 'playwright';
import {once} from 'node:events';
import assert from 'node:assert/strict';
import {createApp} from '../server.mjs';
import {fixtureGLB} from './fixture.mjs';
import {validateGLB} from '../inference.mjs';
import {readFile} from 'node:fs/promises';
const app=createApp({verifyEngineToken:async token=>{assert.equal(token,'test-only-browser-credential');},authenticate:async(email,password)=>{if(email!=='owner@example.test'||password!=='test-only-password')throw Object.assign(new Error('Denied'),{status:401});return{id:'owner',ttl:60000};}});
app.listen(0,'127.0.0.1');await once(app,'listening');const base='http://127.0.0.1:'+app.address().port;
let browser;
try{
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);assert.ok(page.url().endsWith('/login'));
 await page.locator('#email').fill('owner@example.test');await page.locator('#password').fill('test-only-password');
 await page.locator('button[type=submit]').click();await page.waitForURL(base+'/');
 await page.locator('#engine-token').fill('test-only-browser-credential');await page.locator('#engine-connect').click();await page.waitForFunction(()=>document.getElementById('engine-form').hidden);assert.equal(await page.locator('#engine-token').inputValue(),'');await page.locator('#engine-disconnect').click();await page.waitForFunction(()=>!document.getElementById('engine-form').hidden);
 await page.evaluate(()=>{const transfer=new DataTransfer();transfer.items.add(new File([new Uint8Array([137,80,78,71,13,10,26,10,0,0,0,0,73,72,68,82,0,0,0,1,0,0,0,1])],'drop.png',{type:'image/png'}));document.getElementById('photo-drop').dispatchEvent(new DragEvent('drop',{dataTransfer:transfer,bubbles:true,cancelable:true}));});
 await page.waitForFunction(()=>document.getElementById('photo-name').textContent==='drop.png');
 await page.evaluate(bytes=>{const transfer=new DataTransfer();transfer.items.add(new File([new Uint8Array(bytes)],'test-ekipman.glb',{type:'model/gltf-binary'}));document.getElementById('glb-drop').dispatchEvent(new DragEvent('drop',{dataTransfer:transfer,bubbles:true,cancelable:true}));},[...fixtureGLB()]);
 await page.waitForFunction(()=>document.getElementById('part-count').textContent==='2');
 await page.getByRole('option',{name:'Tank',exact:true}).click();
 await page.locator('#position-x').fill('3');await page.locator('#position-x').press('Tab');
 assert.equal(Number(await page.locator('#position-x').inputValue()),3);
 await page.locator('#undo').click();await page.getByRole('option',{name:'Tank',exact:true}).click();assert.equal(Number(await page.locator('#position-x').inputValue()),-1);
 await page.locator('#redo').click();await page.getByRole('option',{name:'Tank',exact:true}).click();assert.equal(Number(await page.locator('#position-x').inputValue()),3);
 await page.locator('#duplicate').click();assert.equal(await page.locator('#part-count').textContent(),'3');
 await page.locator('#delete').click();assert.equal(await page.locator('#part-count').textContent(),'2');
 await page.getByRole('option',{name:'Tank',exact:true}).click();await page.locator('#part-name').fill('Düzeltilmiş tank');await page.locator('#part-name').press('Tab');
 const event=page.waitForEvent('download');await page.locator('#download').click();const download=await event,bytes=await readFile(await download.path());const doc=validateGLB(bytes);
 assert.ok(doc.nodes.some(n=>n.name==='Düzeltilmiş tank'));assert.ok(doc.nodes.some(n=>n.translation?.[0]===3));
 await page.locator('#glb').setInputFiles({name:'roundtrip.glb',mimeType:'model/gltf-binary',buffer:bytes});
 await page.waitForFunction(()=>document.getElementById('model-stats').textContent.includes('2 parça'));
 assert.equal(errors.length,0,errors.join('\n'));
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(100);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'Mobile horizontal overflow');
 await page.locator('#logout').click();await page.waitForURL(base+'/login');
 const noAccess=await page.request.get(base+'/api/session');assert.equal(noAccess.status(),401);
 console.log('BROWSER_TESTS_PASS: login gate, photo/GLB drag-drop import, transforms, undo/redo, duplicate/delete, export round trip, mobile layout, logout');
}finally{await browser?.close();app.closeAllConnections();await new Promise(r=>app.close(r));}
