import * as THREE from 'three';
import { currentDevice } from './device';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { feature } from 'topojson-client';
import atlas from 'world-atlas/countries-110m.json';
type Route={id:string;type:string;from:{lat:number;lon:number};to:{lat:number;lon:number}};
type Point={code:string;lat:number;lon:number;city:string};
export class Globe {
 private readonly earthRadius=2;private readonly cameraFloor=2.18;private visibleCodes?:Set<string>;private routes:Route[]=[];private routeSvg=document.createElementNS('http://www.w3.org/2000/svg','svg');
 private renderer?:THREE.WebGLRenderer;private scene=new THREE.Scene();private camera=new THREE.PerspectiveCamera(40,1,.01,100);private controls?:OrbitControls;private labels=new Map<string,HTMLButtonElement>();private markers=new Map<string,THREE.Mesh>();private canvas=document.createElement('canvas');private zoom:'world'|'turkey'|'airport'='world';private focusPoint={lat:39,lon:34};private flight=0;private visible=true;
 constructor(private host:HTMLElement,private airports:Point[],private select:(code:string)=>void){
  this.scene.background=new THREE.Color(0x02070d);this.canvas.className='globe-fallback';this.host.appendChild(this.canvas);this.routeSvg.classList.add('network-routes-map');this.host.appendChild(this.routeSvg);
  for(const a of airports){const b=document.createElement('button');b.className='globe-pin';b.dataset.kind=a.code==='ADB'?'primary':'standard';b.textContent=a.code.length>7?a.city:a.code;b.title=a.city;b.onclick=e=>{e.stopPropagation();this.select(a.code)};host.appendChild(b);this.labels.set(a.code,b)}
  try{this.renderer=new THREE.WebGLRenderer({antialias:!currentDevice().mobile,alpha:false,powerPreference:currentDevice().mobile?'low-power':'high-performance'});this.renderer.setPixelRatio(currentDevice().pixelRatio);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.08;this.host.prepend(this.renderer.domElement);this.canvas.hidden=true;this.camera.position.copy(this.point(25,20,6.2));this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.dampingFactor=.06;this.controls.enablePan=false;this.controls.minDistance=this.cameraFloor;this.controls.maxDistance=7.2;this.controls.autoRotate=true;this.controls.autoRotateSpeed=.16;
   let returnTimer:number|undefined;this.controls.addEventListener('start',()=>{this.flight++;this.controls!.autoRotate=false;if(returnTimer)clearTimeout(returnTimer)});this.controls.addEventListener('end',()=>{if(returnTimer)clearTimeout(returnTimer);if(this.zoom==='world')returnTimer=window.setTimeout(()=>this.zoom==='world'&&this.focus('world'),2200)});
   const fallback=document.createElement('canvas');fallback.width=2048;fallback.height=1024;this.drawCountries(fallback,0,0,1);const tex=new THREE.CanvasTexture(fallback);tex.colorSpace=THREE.SRGBColorSpace;const mat=new THREE.MeshStandardMaterial({map:tex,roughness:.88,metalness:0,emissive:new THREE.Color(0xffffff),emissiveIntensity:.12});this.scene.add(new THREE.Mesh(new THREE.SphereGeometry(this.earthRadius,96,64),mat));
   new THREE.TextureLoader().load('/textures/earth.jpg',texture=>{texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=this.renderer?.capabilities.getMaxAnisotropy()||1;mat.map?.dispose();mat.map=texture;mat.emissiveMap=texture;mat.needsUpdate=true});
   this.scene.add(new THREE.HemisphereLight(0xe8f7ff,0x173e54,1.85));const sun=new THREE.DirectionalLight(0xfff6df,1.65);sun.position.set(5,3.5,5);this.scene.add(sun);
   const glowMat=new THREE.ShaderMaterial({transparent:true,side:THREE.BackSide,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{glowColor:{value:new THREE.Color(0x49cfff)}},vertexShader:'varying vec3 vNormal;varying vec3 vWorld;void main(){vNormal=normalize(normalMatrix*normal);vec4 w=modelMatrix*vec4(position,1.0);vWorld=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}',fragmentShader:'uniform vec3 glowColor;varying vec3 vNormal;varying vec3 vWorld;void main(){vec3 V=normalize(cameraPosition-vWorld);float rim=pow(1.0-max(dot(vNormal,V),0.0),3.0);gl_FragColor=vec4(glowColor,rim*.48);}'});this.scene.add(new THREE.Mesh(new THREE.SphereGeometry(2.10,96,64),glowMat));
   for(const a of airports){const primary=a.code==='ADB';const m=new THREE.Mesh(new THREE.SphereGeometry(primary?.022:.015,16,12),new THREE.MeshBasicMaterial({color:primary?0xb7ff3c:0x6ee7ff}));m.position.copy(this.point(a.lat,a.lon,2.025));this.scene.add(m);this.markers.set(a.code,m)}
   let down=[0,0];this.renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);this.renderer.domElement.addEventListener('pointerup',e=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>4)return;const r=this.renderer!.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2),this.camera);const hit=ray.intersectObjects([...this.markers.values()])[0];if(hit)for(const [code,m] of this.markers)if(m===hit.object)this.select(code)});let last=0;const loop=(now=0)=>{requestAnimationFrame(loop);if(!this.renderer||!this.visible||document.hidden||(currentDevice().mobile&&now-last<32))return;last=now;this.controls?.update();this.enforceCameraOutsideEarth();this.renderer.render(this.scene,this.camera);this.placeLabels()};loop();
  }catch(e){console.warn('Globe 2D fallback',e);this.renderer=undefined;this.canvas.hidden=false}new ResizeObserver(()=>this.resize()).observe(host);this.resize();let lr=0;const rf=(now:number)=>{requestAnimationFrame(rf);if(!this.visible||document.hidden||now-lr<80)return;lr=now;this.drawRoutes(now)};requestAnimationFrame(rf)
 }
 private enforceCameraOutsideEarth(){const d=this.camera.position.length();if(d>=this.cameraFloor)return;this.camera.position.multiplyScalar(this.cameraFloor/Math.max(d,.001))}
 setLayers(c:Set<string>){this.visibleCodes=c;for(const [code,m] of this.markers)m.visible=c.has(code);this.placeLabels()} setRoutes(r:Route[]){this.routes=r;this.drawRoutes(performance.now())}
 private project(lat:number,lon:number){const w=this.host.clientWidth,h=this.host.clientHeight;if(this.renderer){const p=this.point(lat,lon,2.03),v=p.clone().project(this.camera);return{x:(v.x+1)/2*w,y:(1-v.y)/2*h,visible:p.clone().normalize().dot(this.camera.position.clone().normalize())>.4&&v.z<1}}const z=this.zoom==='world'?1:8;return{x:w/2+(lon-(this.zoom==='world'?0:this.focusPoint.lon))/360*w*z,y:h/2+((this.zoom==='world'?0:this.focusPoint.lat)-lat)/180*h*z,visible:true}}
 private drawRoutes(now:number){this.routeSvg.setAttribute('viewBox',`0 0 ${this.host.clientWidth} ${this.host.clientHeight}`);this.routeSvg.innerHTML=this.routes.map((r,i)=>{const a=this.project(r.from.lat,r.from.lon),b=this.project(r.to.lat,r.to.lon);if(!a.visible||!b.visible)return'';const x=(a.x+b.x)/2,y=(a.y+b.y)/2-Math.min(55,Math.hypot(a.x-b.x,a.y-b.y)*.2),t=((now/10000)+i*.07)%1,c=r.type==='sea'?'#38c5f2':'#ff9e45',px=(1-t)**2*a.x+2*(1-t)*t*x+t*t*b.x,py=(1-t)**2*a.y+2*(1-t)*t*y+t*t*b.y;return`<path d="M${a.x},${a.y}Q${x},${y} ${b.x},${b.y}" fill="none" stroke="${c}" stroke-width="2" stroke-dasharray="5 4"/><circle cx="${px}" cy="${py}" r="4" fill="${c}"/>`}).join('')}
 private point(lat:number,lon:number,r:number){const p=(90-lat)*Math.PI/180,t=(lon+180)*Math.PI/180;return new THREE.Vector3(-r*Math.sin(p)*Math.cos(t),r*Math.cos(p),r*Math.sin(p)*Math.sin(t))}
 show(v:boolean){this.visible=v;if(v)this.resize()}
 focus(mode:'world'|'turkey'|'airport',point?:Point){this.zoom=mode;this.focusPoint=point||{lat:39,lon:34};if(!this.controls){this.resize();return}this.controls.minDistance=this.cameraFloor;this.controls.maxDistance=mode==='world'?7.2:4.8;this.controls.autoRotate=mode==='world';const n=this.point(this.focusPoint.lat,this.focusPoint.lon,1),landscape=this.host.clientWidth>this.host.clientHeight,end=n.clone().multiplyScalar(mode==='world'?(landscape?6.05:6.45):mode==='turkey'?(landscape?3.35:3.7):2.65),target=n.clone().multiplyScalar(mode==='world'?0:1.86),start=this.camera.position.clone(),st=this.controls.target.clone(),token=++this.flight,t=performance.now();const step=(now:number)=>{if(token!==this.flight)return;const k=Math.min(1,(now-t)/1050),q=k*k*(3-2*k);this.camera.position.lerpVectors(start,end,q);this.controls!.target.lerpVectors(st,target,q);this.controls!.update();this.enforceCameraOutsideEarth();if(k<1)requestAnimationFrame(step)};requestAnimationFrame(step)}
 private resize(){const w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;if(this.renderer){this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}else{this.canvas.width=w*1.5;this.canvas.height=h*1.5;const z=this.zoom==='world'?1:8;this.drawCountries(this.canvas,this.zoom==='world'?0:this.focusPoint.lon,this.zoom==='world'?0:this.focusPoint.lat,z)}this.placeLabels()}
 private drawCountries(canvas:HTMLCanvasElement,lon:number,lat:number,zoom:number){const c=canvas.getContext('2d')!,w=canvas.width,h=canvas.height;c.fillStyle='#15506c';c.fillRect(0,0,w,h);c.fillStyle='#448278';c.strokeStyle='#9ccfc4';c.lineWidth=.65;const geo=feature(atlas as never,(atlas as any).objects.countries) as any;const ring=(r:number[][])=>{c.beginPath();r.forEach(([x,y],i)=>{const px=w/2+(x-lon)/360*w*zoom,py=h/2+(lat-y)/180*h*zoom;i?c.lineTo(px,py):c.moveTo(px,py)});c.closePath();c.fill();c.stroke()};for(const f of geo.features){if(f.geometry.type==='Polygon')f.geometry.coordinates.forEach(ring);else if(f.geometry.type==='MultiPolygon')f.geometry.coordinates.forEach((p:number[][][])=>p.forEach(ring))}}
 private placeLabels(){const w=this.host.clientWidth,h=this.host.clientHeight;for(const a of this.airports){const b=this.labels.get(a.code)!;let x:number,y:number,show=true;if(this.renderer){const p=this.point(a.lat,a.lon,2.032),v=p.clone().project(this.camera);x=(v.x+1)/2*w;y=(1-v.y)/2*h;show=p.clone().normalize().dot(this.camera.position.clone().normalize())>.4&&v.z<1&&x>0&&x<w&&y>0&&y<h}else{const z=this.zoom==='world'?1:8,lon=this.zoom==='world'?0:this.focusPoint.lon,lat=this.zoom==='world'?0:this.focusPoint.lat;x=w/2+(a.lon-lon)/360*w*z;y=h/2+(lat-a.lat)/180*h*z}if(this.zoom==='world'&&a.code!=='ADB'&&!['LHR','DXB','JFK'].includes(a.code))show=false;if(this.visibleCodes&&!this.visibleCodes.has(a.code))show=false;const offset:Record<string,[number,number]>={ADB:[-35,-10],BJV:[-25,15],DLM:[5,30],AYT:[20,8],GZP:[32,25],SAW:[12,-25],STAD:[-58,-13],SHELL_DERINCE:[38,9],CEKISAN:[-70,-20],SHELL_ANTALYA:[-62,8]};const[dx,dy]=this.zoom==='world'?[0,0]:offset[a.code]||[0,0];b.hidden=!show;b.style.left=`${x+dx}px`;b.style.top=`${y+dy}px`}}
}
