/** Manufacturer nominal dimensions in metres. Shape details are simplified. */
export type GSESpec={id:string;tr:string;en:string;model:string;type:'bus'|'tractor'|'cart'|'belt';length:number;width:number;height:number;wheelbase?:number;drawingSource?:string;color:string;source:string;noteTr:string;noteEn:string;loaded?:boolean};
const cart={model:'Orientitan · Open Baggage Trailer',type:'cart' as const,length:4.141,width:1.5,height:1.262,color:'#d7e4e6',source:'https://uld-equipment.com/2-1-open-airport-baggage-cart.html',noteTr:'Çeki oku dahil dış ölçü. Tabla: 3 × 1,5 m; yerden 0,56 m. Bagajlar temsili.',noteEn:'Overall size includes drawbar. Deck: 3 × 1.5 m at 0.56 m. Luggage is illustrative.'};
export const GSE_SPECS:Record<string,GSESpec>={
  APRON_BUS:{id:'APRON_BUS',tr:'Apron yolcu otobüsü',en:'Apron passenger bus',model:'TAM VIVAIR 104WL',type:'bus',length:14.72,width:3.17,height:3.1,wheelbase:8.21,drawingSource:'https://www.tam-motors.eu/wp-content/uploads/2018/05/data-sheet_vivair_view_bv_20180205_v2-prodaja-popravki.pdf',color:'#e4ebec',source:'https://www.tam-motors.eu/buses/vivair-104wl/',noteTr:'Klima dahil yükseklik. Her yanda üç çift kanatlı yolcu kapısı olan düzen.',noteEn:'Height includes A/C. Configuration with three double passenger doors per side.'},
  BAGGAGE_TRACTOR:{id:'BAGGAGE_TRACTOR',tr:'Bagaj traktörü',en:'Baggage tractor',model:'MULAG Comet 4D',type:'tractor',length:2.94,width:1.45,height:2.22,wheelbase:1.64,color:'#f0c82f',source:'https://www.mulag.de/en/ground-support-equipment/products/towing-tractors/comet-4d/',noteTr:'Uzunluk çeki kancası hariç; kabinli. Dingil aralığı 1,64 m. Üretici: donanıma göre yaklaşık ±%5.',noteEn:'Length excludes tow hitch; cab fitted. Wheelbase 1.64 m. Manufacturer: approximately ±5% by configuration.'},
  BAGGAGE_CART:{id:'BAGGAGE_CART',tr:'Bagaj römorku · boş',en:'Baggage cart · empty',...cart},
  BAGGAGE_CART_LOADED:{id:'BAGGAGE_CART_LOADED',tr:'Bagaj römorku · dolu',en:'Baggage cart · loaded',...cart,loaded:true},
  BELT_LOADER:{id:'BELT_LOADER',tr:'Bantlı bagaj yükleyici',en:'Baggage belt loader',model:'MULAG Orbiter 7.5',type:'belt',length:7.8,width:2.19,height:2.109,wheelbase:3.1,color:'#e4ebec',source:'https://www.mulag.de/en/ground-support-equipment/products/conveyor-belt-vehicles/orbiter-75/',noteTr:'Kabinli taşıma konumu. Bant 7,5 × 0,6 m; ön uç çalışma yüksekliği en çok 4,125 m (bu sürümde hareketli değil). Donanıma göre yaklaşık ±%5.',noteEn:'Transport position with cab. Belt 7.5 × 0.6 m; front working height up to 4.125 m (not animated in this version). Approximately ±5% by configuration.'}
};
