import './style.css';
import './workspace.css';
import './immersive.css';
import { Globe } from './globe';
import { NetworkPanel, NETWORK_NODES } from './network';
import type { Workspace } from './workspace';
type Lang='tr'|'en';type Airport={code:string;city:string;cityEn:string;lat:number;lon:number;ready:'ready'|'design'|'info';desc:string;descEn:string};
const airports:Airport[]=[{code:'ADB',city:'İzmir Adnan Menderes',cityEn:'İzmir Adnan Menderes',lat:38.2924,lon:27.157,ready:'ready',desc:'Yakıt tesisi ve R14–38K çalışma alanı',descEn:'Fuel facility and R14–38K workspace'},{code:'BJV',city:'Milas–Bodrum',cityEn:'Milas–Bodrum',lat:37.2506,lon:27.6643,ready:'design',desc:'Tesis modeli hazırlanıyor',descEn:'Facility model in design'},{code:'DLM',city:'Dalaman',cityEn:'Dalaman',lat:36.7131,lon:28.7925,ready:'info',desc:'Meydan bilgi noktası',descEn:'Airport information point'},{code:'AYT',city:'Antalya',cityEn:'Antalya',lat:36.8987,lon:30.8005,ready:'info',desc:'Meydan bilgi noktası',descEn:'Airport information point'},{code:'GZP',city:'Gazipaşa',cityEn:'Gazipaşa',lat:36.2992,lon:32.3014,ready:'info',desc:'Meydan bilgi noktası',descEn:'Airport information point'},{code:'SAW',city:'Sabiha Gökçen',cityEn:'Sabiha Gökçen',lat:40.8986,lon:29.3092,ready:'info',desc:'Meydan bilgi noktası',descEn:'Airport information point'}];
const copy={tr:{nav:['Ana Sayfa','Hakkımda','Yetkinlikler','Projeler','Araştırma'],heroKicker:'HAVACILIK • DİJİTAL DÖNÜŞÜM • SİMÜLASYON',heroTitle:'Gerçek operasyon bilgisini etkileşimli 3D eğitime dönüştürüyorum.',heroText:'Havacılık yakıt tesisleri, ikmal araçları ve operasyon süreçleri için tarayıcı tabanlı tasarım, eğitim, tatbikat ve simülasyon platformu.',explore:'3D Dünyayı Keşfet',quick:'ADB Tesise Hızlı Gir',aboutTitle:'Saha deneyimi, akademik araştırma ve dijital üretim.',aboutText:'Havacılık yakıt operasyonları ve dijital üretim odaklı çalışma alanı.'},en:{nav:['Home','About','Expertise','Projects','Research'],heroKicker:'AVIATION • DIGITAL TRANSFORMATION • SIMULATION',heroTitle:'Transforming real operational expertise into interactive 3D training.',heroText:'A browser-based design, training, drill and simulation platform for aviation fuel facilities and operations.',explore:'Explore 3D World',quick:'Quick Entry to ADB',aboutTitle:'Field experience, academic research and digital production.',aboutText:'A workspace focused on aviation fuel operations and digital production.'}};let lang:Lang='tr';try{lang=localStorage.getItem('ks-lang')==='en'?'en':'tr'}catch{}let workspace:Workspace|undefined,loading:Promise<Workspace>|undefined;const t=()=>copy[lang];const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<header class="topbar"><a class="brand" href="#home"><span>KS</span><b>AVIATION</b><small>DIGITAL TWIN</small></a><nav id="nav"></nav><div class="head-actions"><button id="langBtn" class="lang"></button><button id="openAirport" class="login">ADB HAVALİMANI</button></div></header><button id="immersiveFullscreen" class="immersive-fullscreen" title="Tam ekran" aria-label="Tam ekran">⛶</button><main id="landing"><section id="home" class="home"><div class="hero-copy"><div class="eyebrow" id="heroKicker"></div><h1 id="heroTitle"></h1><p id="heroText"></p><div class="hero-actions"><button id="exploreBtn" class="primary"></button><button id="quickBtn" class="secondary"></button></div></div><div class="globe-shell"><div id="globe"></div><div class="globe-controls" aria-label="Harita görünümü"><button id="globeWorld"></button><button id="globeTurkey"></button></div><button id="mapHome" class="map-home" aria-label="Ana sayfaya dön">↩</button><div class="globe-hud"><span class="live">● KS AVIATION</span><b>DÜNYA → TÜRKİYE → ADB</b><small>Meydanı seç → Havalimanı / Tesis / Tasarım</small></div></div></section><section class="about" id="about"><div><span class="section-no">01 / PROFILE</span><h2 id="aboutTitle"></h2></div><p id="aboutText"></p></section><section id="worldPanel" class="world-panel"><div id="airportGrid" class="airport-grid"></div></section></main><section id="workspace" class="workspace" hidden></section><div id="airportCard" class="airport-card hidden"></div>`;
const $=(s:string)=>document.querySelector<HTMLElement>(s)!;const networkPoints=[...airports,...NETWORK_NODES];const globe=new Globe($('#globe'),networkPoints,code=>{const a=airports.find(x=>x.code===code);a?void showAirportCard(a):showNetworkPoint(networkPoints.find(p=>p.code===code)!)});const network=new NetworkPanel($('.globe-shell'),globe,networkPoints,p=>{const a=airports.find(x=>x.code===p.code);a?void showAirportCard(a):showNetworkPoint(p)},()=>{void enterWorld('turkey',true)});
function showNetworkPoint(p:{code:string;city:string;lat:number;lon:number}){globe.focus('airport',p);const c=$('#airportCard');c.classList.remove('hidden');c.innerHTML=`<button class="x">×</button><span>${p.code}</span><h3>${p.city}</h3><p>${p.lat.toFixed(5)}° N · ${p.lon.toFixed(5)}° E</p>`;c.querySelector('.x')!.addEventListener('click',()=>c.classList.add('hidden'))}
function renderCopy(){document.documentElement.lang=lang;$('#nav').innerHTML=t().nav.map((n,i)=>`<a href="${i===0?'#home':i===1?'#about':'#worldPanel'}">${n}</a>`).join('');const v:Record<string,string>={heroKicker:t().heroKicker,heroTitle:t().heroTitle,heroText:t().heroText,exploreBtn:t().explore,quickBtn:t().quick,aboutTitle:t().aboutTitle,aboutText:t().aboutText,langBtn:lang==='tr'?'EN':'TR',openAirport:lang==='tr'?'ADB HAVALİMANI':'ADB AIRPORT',globeWorld:lang==='tr'?'Dünya':'World',globeTurkey:'Türkiye'};Object.entries(v).forEach(([k,x])=>$('#'+k).textContent=x);renderAirports();workspace?.setLanguage(lang);network.setLanguage(lang);$('#mapHome').setAttribute('aria-label',lang==='tr'?'Ana sayfaya dön':'Back to home');$('#mapHome').title=lang==='tr'?'Ana sayfa':'Home';$('#immersiveFullscreen').setAttribute('aria-label',lang==='tr'?'Tam ekran':'Fullscreen');$('#nav').querySelectorAll('a').forEach((a,i)=>a.onclick=e=>{if(i===0){e.preventDefault();void showHome()}})}
function renderAirports(){$('#airportGrid').innerHTML=airports.map(a=>`<button class="airport-tile ${a.ready}" data-code="${a.code}"><span translate="no" class="notranslate">${a.code}</span><div><b>${a.city}</b></div><i>↗</i></button>`).join('');$('#airportGrid').querySelectorAll<HTMLElement>('[data-code]').forEach(el=>el.onclick=()=>void showAirportCard(airports.find(a=>a.code===el.dataset.code)!))}
async function showAirportCard(a:Airport){if(!document.body.classList.contains('world-expanded')&&!await enterWorld('turkey'))return;globe.focus('airport',a);const c=$('#airportCard');c.classList.remove('hidden');c.innerHTML=`<button class="x">×</button><span translate="no" class="notranslate">${a.code} • TÜRKİYE</span><h3>${a.city}</h3><div class="card-actions">${a.code==='ADB'?`<button data-open="airport" class="primary">ADB Havalimanı</button><button data-open="facility" class="secondary">ADB Tesisi</button><button data-open="design" class="secondary">Çizim / Tasarım</button>`:''}</div>`;c.querySelector('.x')!.addEventListener('click',()=>c.classList.add('hidden'));c.querySelectorAll<HTMLElement>('[data-open]').forEach(b=>b.onclick=()=>void openWorkspace(b.dataset.open==='airport'?'airport':'facility',b.dataset.open==='design'))}
async function showHome(){if(workspace&&!await workspace.requestLeave())return;workspace?.hide();$('#workspace').hidden=true;$('#landing').hidden=false;document.body.classList.remove('in-workspace','world-expanded');$('#airportCard').classList.add('hidden');network.browse();globe.show(true);globe.focus('world');scrollTo(0,0)}
async function enterWorld(where:'world'|'turkey'='turkey',keepMode=false){if(workspace&&!await workspace.requestLeave())return false;workspace?.hide();$('#workspace').hidden=true;$('#landing').hidden=false;document.body.classList.remove('in-workspace');document.body.classList.add('world-expanded');$('#airportCard').classList.add('hidden');globe.show(true);if(!keepMode)network.browse();globe.focus(where);$('#globeWorld').classList.toggle('active',where==='world');$('#globeTurkey').classList.toggle('active',where==='turkey');scrollTo(0,0);return true}
async function openWorkspace(mode:'airport'|'facility',edit=false){$('#airportCard').classList.add('hidden');$('#landing').hidden=true;$('#workspace').hidden=false;document.body.classList.remove('world-expanded');document.body.classList.add('in-workspace');globe.show(false);if(!loading){$('#workspace').innerHTML='<div style="padding:40px">ADB çalışma alanı yükleniyor…</div>';loading=import('./workspace').then(async({Workspace})=>{const w=new Workspace($('#workspace'),lang,enterWorld);await w.init();workspace=w;return w})}try{const w=await loading;w.show(mode,edit);w.setLanguage(lang)}catch(e){console.error(e)}}
async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();$('#immersiveFullscreen').textContent=document.fullscreenElement?'×':'⛶'}catch{ /* iOS/browser fallback stays in 100dvh immersive layout */ }}
$('#immersiveFullscreen').onclick=()=>void toggleFullscreen();document.addEventListener('fullscreenchange',()=>{$('#immersiveFullscreen').textContent=document.fullscreenElement?'×':'⛶';globe.show(!document.body.classList.contains('in-workspace'))});$('#langBtn').onclick=()=>{lang=lang==='tr'?'en':'tr';try{localStorage.setItem('ks-lang',lang)}catch{}renderCopy()};$('#exploreBtn').onclick=()=>void enterWorld('world');$('#globeWorld').onclick=()=>void enterWorld('world');$('#globeTurkey').onclick=()=>void enterWorld('turkey');$('#quickBtn').onclick=()=>void openWorkspace('facility');$('#openAirport').onclick=()=>void openWorkspace('airport');$('#mapHome').onclick=()=>void showHome();$('.brand').onclick=e=>{e.preventDefault();void showHome()};renderCopy();

