import './style.css';
import './workspace.css';
import { Globe } from './globe';
import { NetworkPanel, NETWORK_NODES } from './network';
import type { Workspace } from './workspace';

type Lang = 'tr' | 'en';
type Airport = { code:string; city:string; cityEn:string; lat:number; lon:number; ready:'ready'|'design'|'info'; desc:string; descEn:string };

const airports: Airport[] = [
  {code:'ADB',city:'İzmir Adnan Menderes',cityEn:'İzmir Adnan Menderes',lat:38.2924,lon:27.1570,ready:'ready',desc:'Yakıt tesisi ve R14–38K çalışma alanı',descEn:'Fuel facility and R14–38K workspace'},
  {code:'BJV',city:'Milas–Bodrum',cityEn:'Milas–Bodrum',lat:37.2506,lon:27.6643,ready:'design',desc:'Tesis modeli hazırlanıyor',descEn:'Facility model in design'},
  {code:'DLM',city:'Dalaman',cityEn:'Dalaman',lat:36.7131,lon:28.7925,ready:'info',desc:'Meydan bilgi noktası',descEn:'Airport information point'},
  {code:'AYT',city:'Antalya',cityEn:'Antalya',lat:36.8987,lon:30.8005,ready:'info',desc:'Meydan bilgi noktası',descEn:'Airport information point'},
  {code:'GZP',city:'Gazipaşa',cityEn:'Gazipaşa',lat:36.2992,lon:32.3014,ready:'info',desc:'Meydan bilgi noktası',descEn:'Airport information point'},
  {code:'SAW',city:'Sabiha Gökçen',cityEn:'Sabiha Gökçen',lat:40.8986,lon:29.3092,ready:'info',desc:'Meydan bilgi noktası',descEn:'Airport information point'}
];

const copy = {
 tr:{nav:['Ana Sayfa','Hakkımda','Yetkinlikler','Projeler','Araştırma'],heroKicker:'HAVACILIK • DİJİTAL DÖNÜŞÜM • SİMÜLASYON',heroTitle:'Gerçek operasyon bilgisini etkileşimli 3D eğitime dönüştürüyorum.',heroText:'Havacılık yakıt tesisleri, ikmal araçları ve operasyon süreçleri için tarayıcı tabanlı tasarım, eğitim, tatbikat ve simülasyon platformu.',explore:'3D Dünyayı Keşfet',quick:'ADB Tesise Hızlı Gir',worldTitle:'Operasyon dünyası',worldText:'Küreyi döndürün, Türkiye üzerindeki bir meydanı seçin veya ADB çalışma alanına doğrudan geçin.',aboutTitle:'Saha deneyimi, akademik araştırma ve dijital üretim.',aboutText:'Kenan Seyhan; havacılık yakıt operasyonları, tesis süreçleri, stok yönetimi, kalite kontrol, uçak ikmali ve operasyonel emniyet alanlarında saha deneyimine sahip bir havacılık profesyonelidir. Ege Üniversitesi Üretim Teknolojisinde Dijitalleşme yüksek lisans programında çalışmalarını sürdürmektedir.',facility:'ADB ÇALIŞMA MERKEZİ',back:'Dünyaya Dön',continue:'Çalışmaya Devam Et',rightClick:'Sağ tık: hızlı menü • Çift tık: doğrudan ADB tesisi',modes:['İncele','Tasarla','3D Studio','Senaryo','Tatbikat','Operasyon'],modeDesc:['Nesneleri, sistemleri ve kontrol noktalarını etkileşimli inceleyin.','Tesisi ve ekipmanı ekleyin, taşıyın, döndürün ve sürümleyin.','Fotoğraf, video ve GLB varlıklarını üretim hattına alın.','Adımları, kuralları, arızaları ve başarı ölçütlerini oluşturun.','Yardım azaltılmış emniyet ve acil durum çalışmaları yürütün.','Dolumdan uçak ikmaline kadar gerçekçi akışı uygulayın.']},
 en:{nav:['Home','About','Expertise','Projects','Research'],heroKicker:'AVIATION • DIGITAL TRANSFORMATION • SIMULATION',heroTitle:'Transforming real operational expertise into interactive 3D training.',heroText:'A browser-based design, training, drill and simulation platform for aviation fuel facilities, refuelling vehicles and operational processes.',explore:'Explore 3D World',quick:'Quick Entry to ADB',worldTitle:'Operations world',worldText:'Rotate the globe, select an airport over Türkiye or jump directly to the ADB workspace.',aboutTitle:'Field experience, academic research and digital production.',aboutText:'Kenan Seyhan is an aviation professional with field experience in aviation fuel operations, facility processes, inventory control, quality control, aircraft refuelling and operational safety. He is pursuing a master’s degree in Digitalization in Production Technology at Ege University.',facility:'ADB WORKSPACE',back:'Back to World',continue:'Continue Working',rightClick:'Right click: quick menu • Double click: direct ADB entry',modes:['Inspect','Design','3D Studio','Scenario','Drill','Operation'],modeDesc:['Inspect objects, systems and control points interactively.','Add, move, rotate and version facilities and equipment.','Process photo, video and GLB assets through the production pipeline.','Create steps, rules, failures and success criteria.','Run safety and emergency exercises with reduced assistance.','Perform a realistic flow from loading to aircraft refuelling.']}
};

let lang:Lang='tr';try{lang=localStorage.getItem('ks-lang')==='en'?'en':'tr';}catch{}
let workspace:Workspace|undefined;let loading:Promise<Workspace>|undefined;
const t=()=>copy[lang];
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<header class="topbar"><a class="brand" href="#home"><span>KS</span><b>AVIATION</b><small>DIGITAL TWIN</small></a><nav id="nav"></nav><div class="head-actions"><button id="langBtn" class="lang"></button><button id="openAirport" class="login">ADB HAVALİMANI</button></div></header>
<main id="landing"><section id="home" class="home"><div class="hero-copy"><div class="eyebrow" id="heroKicker"></div><h1 id="heroTitle"></h1><p id="heroText"></p><div class="hero-actions"><button id="exploreBtn" class="primary"></button><button id="quickBtn" class="secondary"></button></div><div class="status-row"><span><i class="dot green"></i> ADB • AIRPORT + FACILITY</span><span>R14 • 38K</span><span>DESIGN WORKSPACE</span></div></div><div class="globe-shell"><div id="globe"></div><div class="globe-controls"><button id="globeWorld"></button><button id="globeTurkey"></button></div><div class="globe-hud"><span class="live">● KS AVIATION</span><b id="globeCaption">DÜNYA → TÜRKİYE → ADB</b><small id="rightClick"></small></div></div></section>
<section class="about" id="about"><div><span class="section-no">01 / PROFILE</span><h2 id="aboutTitle"></h2></div><p id="aboutText"></p><div class="skills"><span>AVIATION FUEL OPERATIONS</span><span>QUALITY CONTROL</span><span>3D SIMULATION</span><span>DIGITAL TRANSFORMATION</span><span>OPERATIONAL SAFETY</span><span>AI-ASSISTED TRAINING</span></div></section><section id="worldPanel" class="world-panel"><div class="world-head"><div><span class="section-no">02 / 3D WORLD</span><h2 id="worldTitle"></h2><p id="worldText"></p></div><button id="worldQuick" class="primary"></button></div><div id="airportGrid" class="airport-grid"></div></section></main>
<section id="workspace" class="workspace" hidden></section><div id="airportCard" class="airport-card hidden"></div>`;
const $=(s:string)=>document.querySelector<HTMLElement>(s)!;
const networkPoints=[...airports,...NETWORK_NODES];const globe=new Globe($('#globe'),networkPoints,code=>{const airport=airports.find(a=>a.code===code);if(airport)void showAirportCard(airport);else showNetworkPoint(networkPoints.find(p=>p.code===code)!);});const network=new NetworkPanel($('.globe-shell'),globe,networkPoints,p=>{const airport=airports.find(a=>a.code===p.code);if(airport)void showAirportCard(airport);else showNetworkPoint(p);});
function showNetworkPoint(p:{code:string;city:string;lat:number;lon:number}){globe.focus('airport',p);const c=$('#airportCard');c.classList.remove('hidden');c.innerHTML=`<button class="x" aria-label="Kapat">×</button><span>${p.code}</span><h3>${p.city}</h3><p>${p.lat.toFixed(5)}° N · ${p.lon.toFixed(5)}° E</p><p>${lang==='tr'?'Operasyon ağı konumu · 3D tesis modeli henüz eklenmedi.':'Operations network location · 3D facility model is not yet available.'}</p>`;c.querySelector('.x')!.addEventListener('click',()=>c.classList.add('hidden'));}
function renderCopy(){document.documentElement.lang=lang;$('#nav').innerHTML=t().nav.map((n,i)=>`<a href="${i===0?'#home':i===1?'#about':'#worldPanel'}">${n}</a>`).join('');
 const vals:Record<string,string>={heroKicker:t().heroKicker,heroTitle:t().heroTitle,heroText:t().heroText,exploreBtn:t().explore,quickBtn:t().quick,aboutTitle:t().aboutTitle,aboutText:t().aboutText,worldTitle:t().worldTitle,worldText:t().worldText,worldQuick:t().quick,langBtn:lang==='tr'?'EN':'TR',openAirport:lang==='tr'?'ADB HAVALİMANI':'ADB AIRPORT',globeWorld:lang==='tr'?'Dünya':'World',globeTurkey:'Türkiye',globeCaption:lang==='tr'?'DÜNYA → TÜRKİYE → ADB':'WORLD → TÜRKİYE → ADB',rightClick:lang==='tr'?'Meydanı seç → Havalimanı / Tesis / Tasarım':'Select an airport → Airport / Facility / Design'};
 Object.entries(vals).forEach(([k,v])=>$('#'+k).textContent=v);renderAirports();workspace?.setLanguage(lang);network.setLanguage(lang);
 $('#nav').querySelectorAll('a').forEach((a,i)=>a.onclick=e=>{if(i===0){e.preventDefault();showHome();}else if(document.body.classList.contains('world-expanded')||document.body.classList.contains('in-workspace'))showHome();});
}
function renderAirports(){$('#airportGrid').innerHTML=airports.map(a=>`<button class="airport-tile ${a.ready}" data-code="${a.code}"><span>${a.code}</span><div><b>${a.city}</b><small>${lang==='tr'?a.desc:a.descEn}</small></div><i>↗</i></button>`).join('');$('#airportGrid').querySelectorAll<HTMLElement>('[data-code]').forEach(el=>{el.onclick=()=>showAirportCard(airports.find(a=>a.code===el.dataset.code)!);el.oncontextmenu=e=>{e.preventDefault();showAirportCard(airports.find(a=>a.code===el.dataset.code)!);};});}
async function showAirportCard(a:Airport){if(!document.body.classList.contains('world-expanded')){if(!await enterWorld('turkey'))return;}globe.focus('airport',a);const c=$('#airportCard');c.classList.remove('hidden');c.innerHTML=`<button class="x" aria-label="Kapat">×</button><span>${a.code} • TÜRKİYE</span><h3>${a.city}</h3><p>${a.code==='ADB'?(lang==='tr'?'Havalimanı uydu haritası, yakıt tesisi ve çizim çalışma alanı.':'Airport satellite map, fuel facility and design workspace.'):(lang==='tr'?a.desc:a.descEn)}</p><div class="card-actions">${a.code==='ADB'?`<button data-open="airport" class="primary">${lang==='tr'?'ADB Havalimanı':'ADB Airport'}</button><button data-open="facility" class="secondary">${lang==='tr'?'ADB Tesisi':'ADB Facility'}</button><button data-open="design" class="secondary">${lang==='tr'?'Çizim / Tasarım':'Draw / Design'}</button>`:`<button class="secondary" data-close>${lang==='tr'?'Haritada incele':'Inspect on map'}</button>`}</div>`;c.querySelector('.x')!.addEventListener('click',()=>c.classList.add('hidden'));c.querySelector('[data-close]')?.addEventListener('click',()=>c.classList.add('hidden'));c.querySelectorAll<HTMLElement>('[data-open]').forEach(b=>b.onclick=()=>void openWorkspace(b.dataset.open==='airport'?'airport':'facility',b.dataset.open==='design'));}
async function showHome(){if(workspace&&!await workspace.requestLeave())return;workspace?.hide();$('#workspace').hidden=true;$('#landing').hidden=false;document.body.classList.remove('in-workspace','world-expanded');$('#airportCard').classList.add('hidden');globe.show(true);globe.focus('world');window.scrollTo({top:0,behavior:'smooth'});}
async function enterWorld(where:'world'|'turkey'='turkey'){if(workspace&&!await workspace.requestLeave())return false;workspace?.hide();$('#workspace').hidden=true;$('#landing').hidden=false;document.body.classList.remove('in-workspace');document.body.classList.add('world-expanded');$('#airportCard').classList.add('hidden');globe.show(true);globe.focus(where);$('#globeWorld').classList.toggle('active',where==='world');$('#globeTurkey').classList.toggle('active',where==='turkey');window.scrollTo(0,0);return true;}
async function openWorkspace(mode:'airport'|'facility',edit=false){
 
 $('#airportCard').classList.add('hidden');$('#landing').hidden=true;$('#workspace').hidden=false;document.body.classList.remove('world-expanded');document.body.classList.add('in-workspace');globe.show(false);window.scrollTo(0,0);
 if(!loading){$('#workspace').innerHTML=`<div style="padding:40px">${lang==='tr'?'ADB çalışma alanı yükleniyor…':'Loading ADB workspace…'}</div>`;loading=import('./workspace').then(async({Workspace})=>{const w=new Workspace($('#workspace'),lang,enterWorld);await w.init();workspace=w;return w;}).catch(err=>{console.error(err);loading=undefined;$('#workspace').innerHTML=`<div style="padding:40px"><p>${lang==='tr'?'Çalışma alanı yüklenemedi. Bağlantıyı kontrol edip tekrar deneyin.':'The workspace could not load. Check your connection and retry.'}</p><button id="retryWorkspace">${lang==='tr'?'Tekrar dene':'Retry'}</button><button id="returnHome">${lang==='tr'?'Ana sayfa':'Home'}</button></div>`;$('#retryWorkspace').onclick=()=>void openWorkspace(mode,edit);$('#returnHome').onclick=showHome;throw err;});}
 try{const w=await loading;w.show(mode,edit);w.setLanguage(lang);}catch{}
}
$('#langBtn').onclick=()=>{lang=lang==='tr'?'en':'tr';try{localStorage.setItem('ks-lang',lang);}catch{}renderCopy();$('#airportCard').classList.add('hidden');};$('#exploreBtn').onclick=()=>enterWorld('turkey');$('#globeWorld').onclick=()=>enterWorld('world');$('#globeTurkey').onclick=()=>enterWorld('turkey');$('#quickBtn').onclick=()=>void openWorkspace('facility');$('#worldQuick').onclick=()=>void openWorkspace('facility');$('#openAirport').onclick=()=>void openWorkspace('airport');$('.brand').onclick=e=>{e.preventDefault();showHome();};renderCopy();
