import * as THREE from 'three';
import { AIRPORT_CENTER } from './geo';
export type GroundPhoto={enabled:boolean;x:number;z:number;width:number;height:number;rotation:number;opacity:number};
// An oblique illustration cannot be made into survey imagery with a single transform.
export const DEFAULT_PHOTO:GroundPhoto={enabled:false,x:AIRPORT_CENTER[0],z:AIRPORT_CENTER[1],width:3700,height:1233,rotation:-103,opacity:1};
export function validatePhoto(value:unknown):GroundPhoto{
  const p=value as Partial<GroundPhoto>|undefined,out={...DEFAULT_PHOTO};if(!p)return out;
  out.enabled=p.enabled===true;for(const key of ['x','z','width','height','rotation','opacity'] as const){const n=p[key];if(typeof n==='number'&&Number.isFinite(n))out[key]=n;}
  out.x=Math.max(-50000,Math.min(50000,out.x));out.z=Math.max(-50000,Math.min(50000,out.z));out.width=Math.max(100,Math.min(15000,out.width));out.height=Math.max(100,Math.min(15000,out.height));out.rotation=((out.rotation%360)+540)%360-180;out.opacity=Math.max(.1,Math.min(1,out.opacity));return out;
}
export function photoToWorld(p:GroundPhoto,u:number,v:number):[number,number]{const a=p.rotation*Math.PI/180,x=(u-.5)*p.width,z=(v-.5)*p.height;return[p.x+Math.cos(a)*x-Math.sin(a)*z,p.z+Math.sin(a)*x+Math.cos(a)*z];}
export class PhotoGround{
  group=new THREE.Group();private image?:HTMLImageElement;private mesh?:THREE.Mesh;private loaded=false;private failed=false;private lang:'tr'|'en'='tr';readonly element=document.createElement('aside');private config={...DEFAULT_PHOTO};
  constructor(host:HTMLElement,private read:()=>GroundPhoto|undefined,private change:(p:GroundPhoto)=>void,private redraw:()=>void,private focus:(p:GroundPhoto)=>void){this.element.className='ws-photo-panel';this.element.hidden=true;host.appendChild(this.element);}
  private t(tr:string,en:string){return this.lang==='tr'?tr:en;}
  setLanguage(lang:'tr'|'en'){this.lang=lang;if(!this.element.hidden)this.render();}
  toggle(){this.element.hidden=!this.element.hidden;if(!this.element.hidden)this.render();}
  sync(){this.config=validatePhoto(this.read());const p=this.config;this.group.visible=p.enabled;if(p.enabled&&!this.image)this.load();this.group.position.set(p.x,-.022,p.z);this.group.rotation.y=-p.rotation*Math.PI/180;this.group.scale.set(p.width,1,p.height);if(this.mesh)(this.mesh.material as THREE.MeshBasicMaterial).opacity=p.opacity;if(!this.element.hidden)this.render();}
  private load(){const img=new Image();this.image=img;img.onload=()=>{this.loaded=true;const texture=new THREE.Texture(img);texture.colorSpace=THREE.SRGBColorSpace;texture.needsUpdate=true;const material=new THREE.MeshBasicMaterial({map:texture,transparent:true,opacity:this.config.opacity,depthWrite:false});this.mesh=new THREE.Mesh(new THREE.PlaneGeometry(1,1),material);this.mesh.rotation.x=-Math.PI/2;this.group.add(this.mesh);this.redraw();if(!this.element.hidden)this.render();};img.onerror=()=>{this.failed=true;if(!this.element.hidden)this.render();};img.src='/textures/adb-ground-clean.webp';}
  draw(c:CanvasRenderingContext2D){if(!this.config.enabled||!this.loaded||!this.image)return;const p=this.config;c.save();c.translate(p.x,p.z);c.rotate(p.rotation*Math.PI/180);c.globalAlpha=p.opacity;c.drawImage(this.image,-p.width/2,-p.height/2,p.width,p.height);c.restore();}
  private render(){const p=validatePhoto(this.read());this.element.innerHTML=`<header><strong>${this.t('ADB fotoğraf zemini','ADB photo ground')}</strong><button data-photo="close" aria-label="${this.t('Zemin panelini kapat','Close ground panel')}">×</button></header><p>${this.t('Gönderdiğiniz görseldeki uçaklar ve yazılar temizlendi. Bu eğik görüntü ölçüm haritası değildir; aşağıdaki hizalama yaklaşık yerleşim içindir.','Aircraft and labels were removed from your image. This oblique image is not a survey map; the alignment below is approximate.')}</p><label class="ws-check"><input type="checkbox" ${p.enabled?'checked':''} data-photo-enable>${this.t('Fotoğraf zeminini göster','Show photo ground')}</label>${p.enabled?`<small>${this.failed?this.t('Görsel yüklenemedi.','Image could not load.'):this.loaded?this.t('Görsel hazır','Image ready'):this.t('Görsel yükleniyor…','Loading image…')}</small>`:''}<form><div class="ws-photo-fields">${(['x','z','width','height','rotation','opacity'] as const).map(k=>`<label>${({x:'X (m)',z:'Z (m)',width:this.t('Genişlik (m)','Width (m)'),height:this.t('Derinlik (m)','Depth (m)'),rotation:this.t('Dönüş (°)','Rotation (°)'),opacity:this.t('Opaklık 0,1–1','Opacity 0.1–1')})[k]}<input name="${k}" type="number" step="any" required value="${p[k]}" ${k==='opacity'?'min="0.1" max="1"':k==='width'||k==='height'?'min="100" max="15000"':''}></label>`).join('')}</div><button type="submit">${this.t('Hizalamayı uygula','Apply alignment')}</button></form><div class="ws-row"><button data-photo="focus">${this.t('Fotoğrafa git','Focus photo')}</button><button data-photo="reset">${this.t('İlk hizalama','Initial alignment')}</button></div><small>${this.t('Konumlar ve nesneler değişmez. Hizalama tarayıcıya ve JSON yedeğine kaydedilir. Uyduyu açık tutup opaklığı azaltarak karşılaştırabilirsiniz.','Objects retain their coordinates. Alignment is saved in this browser and JSON exports. Keep satellite imagery enabled and lower opacity to compare.')}</small>`;
    this.element.querySelector<HTMLInputElement>('[data-photo-enable]')!.onchange=e=>this.change({...p,enabled:(e.target as HTMLInputElement).checked});
    this.element.querySelector<HTMLFormElement>('form')!.onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement),next={...p};for(const k of ['x','z','width','height','rotation','opacity'] as const)next[k]=Number(f.get(k));this.change(validatePhoto(next));};
    this.element.querySelectorAll<HTMLButtonElement>('[data-photo]').forEach(b=>b.onclick=()=>{if(b.dataset.photo==='close')this.toggle();if(b.dataset.photo==='focus'){if(!p.enabled)this.change({...p,enabled:true});this.focus(p);}if(b.dataset.photo==='reset')this.change({...DEFAULT_PHOTO,enabled:p.enabled});});
  }
}
