type P={code:string;name:string;lat:number;lon:number;kind:'airport'|'storage'|'aliaga'};
const points:P[]=[
{code:'ADB',name:'İzmir Adnan Menderes',lat:38.2924,lon:27.157,kind:'airport'},{code:'BJV',name:'Milas–Bodrum',lat:37.2506,lon:27.6643,kind:'airport'},{code:'DLM',name:'Dalaman',lat:36.7131,lon:28.7925,kind:'airport'},{code:'AYT',name:'Antalya',lat:36.8987,lon:30.8005,kind:'airport'},{code:'GZP',name:'Gazipaşa',lat:36.2992,lon:32.3014,kind:'airport'},{code:'SAW',name:'Sabiha Gökçen',lat:40.8986,lon:29.3092,kind:'airport'},{code:'ESB',name:'Ankara Esenboğa',lat:40.1281,lon:32.9951,kind:'airport'},{code:'IST',name:'İstanbul Havalimanı',lat:41.2753,lon:28.7519,kind:'airport'},
{code:'STAD',name:'STAD',lat:38.77369014256039,lon:26.934985845352717,kind:'storage'},{code:'SHELL_DERINCE',name:'Shell Derince',lat:40.75091382676806,lon:29.84143928846036,kind:'storage'},{code:'CEKISAN',name:'Akdeniz Antalya',lat:36.833929561167764,lon:30.608310104733643,kind:'storage'},{code:'SHELL_ANTALYA',name:'Shell Antalya',lat:36.84010154021184,lon:30.601020997984982,kind:'storage'},{code:'KIRIKKALE',name:'Kırıkkale',lat:39.742613564257525,lon:33.45950705873421,kind:'storage'},{code:'STAR',name:'STAR',lat:38.79846944238605,lon:26.928110595144215,kind:'aliaga'},{code:'PETKIM',name:'Petkim',lat:38.78602081112696,lon:26.93490712857334,kind:'aliaga'},{code:'S_BINA',name:'S Bina',lat:38.78906551429275,lon:26.94969317741288,kind:'aliaga'}];
const B={west:24.1,east:45.0,north:43.0,south:34.2};
class TurkeyView{
 private root=document.createElement('div');private canvas=document.createElement('canvas');private pins=document.createElement('div');private back=document.createElement('button');private img=new Image();private ro?:ResizeObserver;private active=false;private visible=new Set(points.filter(p=>p.kind==='airport'||p.kind==='storage').map(p=>p.code));
 constructor(){this.root.className='turkey-flat-view';this.canvas.className='turkey-flat-canvas';this.pins.className='turkey-flat-pins';this.back.className='turkey-world-back';this.back.textContent='← Dünya';this.back.setAttribute('aria-label','Dünya görünümüne dön');this.root.append(this.canvas,this.pins,this.back);this.img.src='/textures/earth.jpg';this.img.onload=()=>this.draw();this.installStyle();this.bind();}
 private host(){return document.querySelector<HTMLElement>('.globe-shell')}
 private bind(){document.addEventListener('click',e=>{const t=e.target as HTMLElement;if(t.closest('#globeTurkey'))setTimeout(()=>this.show(),0);if(t.closest('#globeWorld')||t.closest('.brand'))this.hide();},true);this.back.onclick=e=>{e.stopPropagation();this.hide();document.querySelector<HTMLButtonElement>('#globeWorld')?.click()};window.addEventListener('ks:map-layers',((e:CustomEvent)=>{this.visible=new Set(e.detail?.visible||[]);if(this.active)this.placePins(this.frame()!);}) as EventListener);new MutationObserver(()=>{if(!document.body.classList.contains('world-expanded'))this.hide()}).observe(document.body,{attributes:true,attributeFilter:['class']});}
 show(){const h=this.host();if(!h)return;this.active=true;if(!this.root.isConnected)h.appendChild(this.root);this.root.classList.add('active');h.classList.add('turkey-flat-active');this.ro??=new ResizeObserver(()=>this.draw());this.ro.observe(h);this.draw();}
 hide(){this.active=false;this.root.classList.remove('active');this.host()?.classList.remove('turkey-flat-active')}
 private frame(){const h=this.host();if(!h)return null;const W=h.clientWidth,H=h.clientHeight,pad=Math.max(18,Math.min(W,H)*.035),mapAspect=(B.east-B.west)/(B.north-B.south),availW=W-pad*2,availH=H-pad*2;let w=availW,hgt=w/mapAspect;if(hgt>availH){hgt=availH;w=hgt*mapAspect}return{W,H,x:(W-w)/2,y:(H-hgt)/2,w,h:hgt}}
 private draw(){if(!this.active||!this.img.complete)return;const f=this.frame();if(!f)return;const d=Math.min(devicePixelRatio||1,2),c=this.canvas;c.width=f.W*d;c.height=f.H*d;c.style.width=f.W+'px';c.style.height=f.H+'px';const g=c.getContext('2d')!;g.setTransform(d,0,0,d,0,0);g.fillStyle='#02070d';g.fillRect(0,0,f.W,f.H);const iw=this.img.naturalWidth,ih=this.img.naturalHeight,sx=(B.west+180)/360*iw,sy=(90-B.north)/180*ih,sw=(B.east-B.west)/360*iw,sh=(B.north-B.south)/180*ih;g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';g.drawImage(this.img,sx,sy,sw,sh,f.x,f.y,f.w,f.h);g.fillStyle='rgba(2,7,13,.06)';g.fillRect(f.x,f.y,f.w,f.h);this.placePins(f)}
 private placePins(f:{x:number;y:number;w:number;h:number}|null){if(!f)return;this.pins.innerHTML='';for(const p of points){if(!this.visible.has(p.code))continue;const b=document.createElement('button');b.className=`turkey-pin ${p.kind} ${p.code==='ADB'?'primary':''}`;b.title=p.name;b.innerHTML=`<i></i><span>${p.code==='SHELL_DERINCE'?'DERİNCE':p.code==='SHELL_ANTALYA'?'SHELL AYT':p.code==='CEKISAN'?'AKDENİZ':p.code}</span>`;b.style.left=`${f.x+(p.lon-B.west)/(B.east-B.west)*f.w}px`;b.style.top=`${f.y+(B.north-p.lat)/(B.north-B.south)*f.h}px`;b.onclick=e=>{e.stopPropagation();this.hide();const candidates=[...document.querySelectorAll<HTMLButtonElement>('.globe-pin')];const target=candidates.find(x=>x.textContent?.trim()===p.code||x.title===p.name||x.textContent?.trim()===p.name);target?.click()};this.pins.appendChild(b)}}
 private installStyle(){const s=document.createElement('style');s.textContent=`.turkey-flat-view{position:absolute;inset:0;z-index:18;background:#02070d;display:none;overflow:hidden}.turkey-flat-view.active{display:block}.turkey-flat-canvas,.turkey-flat-pins{position:absolute;inset:0;width:100%;height:100%}.turkey-flat-pins{pointer-events:none}.turkey-world-back{position:absolute;z-index:24;left:14px;top:14px;border:1px solid #315868;border-radius:7px;background:rgba(4,24,32,.9);color:#e8fbff;padding:8px 11px;font:700 12px system-ui;cursor:pointer;box-shadow:0 3px 14px rgba(0,0,0,.28)}.turkey-world-back:hover{border-color:#a8ff2f;color:#a8ff2f}.turkey-pin{position:absolute;transform:translate(-50%,-50%);pointer-events:auto;border:0;background:transparent;color:#dff7ff;padding:0;display:flex;align-items:center;gap:5px;white-space:nowrap;font:700 10px/1 system-ui;text-shadow:0 1px 3px #000}.turkey-pin i{display:block;width:12px;height:12px;border-radius:50%;background:#69ddf5;border:2px solid #061318;box-shadow:0 0 0 1px #69ddf5}.turkey-pin.storage i{background:#ff9e45;box-shadow:0 0 0 1px #ff9e45}.turkey-pin.aliaga i{background:#2ecbff;box-shadow:0 0 0 1px #2ecbff}.turkey-pin.primary i{width:16px;height:16px;background:#b7ff3c;box-shadow:0 0 0 2px #b7ff3c}.turkey-pin.primary span{color:#b7ff3c}.turkey-flat-active>canvas,.turkey-flat-active>.globe-fallback,.turkey-flat-active>.network-routes-map,.turkey-flat-active>.globe-pin{visibility:hidden!important}.turkey-flat-active .turkey-flat-view,.turkey-flat-active .turkey-flat-view *{visibility:visible!important}@media(max-width:700px){.turkey-world-back{left:8px;top:8px;padding:7px 9px;font-size:11px}.turkey-pin{font-size:8px;gap:3px}.turkey-pin i{width:9px;height:9px}.turkey-pin.primary i{width:12px;height:12px}}`;document.head.appendChild(s)}
}
new TurkeyView();
