import {clickApproachOffset,configureWorkspaceOrbit,constrainCameraHeight} from './camera-navigation';
import {CabDrivingView} from './cab-driving-view';
import {VehicleAudio} from './vehicle-audio';
import {advanceSimulation} from './simulation-clock';
import {FacilityGates,isFacilityGate,setGateOpening} from './facility-gates';
import {RouteHandles} from './route-handles';
import type {RouteDisplay} from './route-planning';
import { R14 } from './r14-spec';
import { isRefueller, numberRefueller, refuellerDimensions } from './refueller-series';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { TransformControls } from 'three/examples/jsm/controls/TransformControls.js';
import { GLTFLoader, type GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { clone as cloneModel } from 'three/examples/jsm/utils/SkeletonUtils.js';
import { makeObject, applyTransform, disposeObject } from './objects';
import { CATALOG, SceneHistory, importScene, validateScene, newEntity, moveEntities, id, groundModes, type GroundMode, type Entity } from './scene-data';
import { Imagery, MapPlane, PlanMap } from './maps';
import { AIRPORT_CENTER, FACILITY_CENTER, geographic } from './geo';
import { AircraftServices } from './aircraft-services';
import { PhotoGround, validatePhoto } from './photo-ground';
import { currentDevice } from './device';
import { GSELibrary } from './gse-library';
import './workspace.css';
import { StaticGround, GROUND_BOUNDS } from './static-ground';
import { FreeCamera } from './free-camera';
import { DesignSession } from './design-session';
import { airportFrame,AIRPORT_TARGET,cameraOffset } from './airport-view';
import { closedAnimationPack } from './model-animations';
import { VehicleLighting } from './vehicle-lighting';
import { VehicleRig } from './vehicle-rig';
import { DrivingPanel } from './driving-panel';
import { CloudPanel } from './cloud-panel';
import type { AuthCallback } from './auth-callback';
import './driving.css';
import { portraitInput,syncPortraitLock } from './portrait-lock';
type Lang='tr'|'en';
const STORE='KS_DIGITAL_TWIN_ADB_V1';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const labels:Record<string,[string,string]>={free:['Serbest dolaşım','Free navigation'],orbit:['Nesne etrafında dön','Orbit object'],cloud:['Bulut kayıt / hesap','Cloud save / account'],drive:['Sürüş / Güzergâh','Drive / Route'],save:['Kaydet','Save'],discard:['Kaydetmeden çık','Discard & exit'],finishEdit:['Tasarımı kapat','Close design'],ortho:['Ortak sabit zemin','Shared static ground'],copy:['Kopyala','Copy'],paste:['Yapıştır','Paste'],width:['En (m)','Width (m)'],length:['Boy (m)','Length (m)'],bodyHeight:['Gövde yüksekliği (m)','Body height (m)'],radius:['Tank yarıçapı (m)','Tank radius (m)'],thickness:['Kalınlık (m)','Thickness (m)'],door:['Kapı konumu','Door position'],longSide:['Uzun kenarda','Long side'],shortSide:['Kısa kenarda','Short side'],services:['Uçak servis noktaları','Aircraft services'],library:['Uçak / araç kütüphanesi','Aircraft / GSE library'],closePanel:['Paneli kapat','Close panel'],groundMode:['Zemin','Ground'],photoGround:['ADB fotoğrafı','ADB photo'],overlayGround:['Fotoğraf + uydu','Photo + satellite'],plainGround:['Düz zemin','Plain ground'],photo:['Zemin ayarı','Ground setup'],world:['Dünya','World'],turkey:['Türkiye','Türkiye'],airport:['ADB Havalimanı','ADB Airport'],facility:['ADB Tesisi','ADB Facility'],design:['Çizim / Tasarım','Draw / Design'],inspect:['İncele','Inspect'],objects:['Nesneler ve gruplar','Objects and groups'],add:['Nesne ekle / çiz','Add / draw'],place:['Haritada yerleştir','Place on map'],center:['Merkeze ekle','Add at center'],finish:['Çizimi bitir','Finish drawing'],cancel:['Vazgeç','Cancel'],satellite:['Uydu haritası','Satellite map'],top:['Üstten bak','Top view'],focus:['Seçilene git','Focus selected'],vehicle:['İkmal aracına git','Focus refueller'],fuelLitres:['Başlangıç doluluğu (L)','Initial fuel volume (L)'],translate:['Taşı (W)','Move (W)'],rotate:['Döndür (E)','Rotate (E)'],scale:['Ölçekle (R)','Scale (R)'],undo:['Geri al','Undo'],redo:['İleri al','Redo'],duplicate:['Çoğalt','Duplicate'],remove:['Sil','Delete'],ground:['Zemine oturt','Ground'],group:['Grupla','Group'],ungroup:['Grubu çöz','Ungroup'],export:['JSON dışarı aktar','Export JSON'],import:['JSON içeri al','Import JSON'],name:['Nesne adı','Object name'],heading:['Yön (°)','Heading (°)'],size:['Ölçek','Scale'],height:['Yükseklik (m)','Elevation (m)'],color:['Renk','Color'],apply:['Değişiklikleri uygula','Apply changes'],selected:['Seçili nesne','Selected object'],search:['Nesne ara…','Search objects…'],groupName:['Grup adı','Group name'],saveCamera:['Kamerayı kaydet','Save camera'],restoreCamera:['Kayıtlı kamera','Saved camera']};
export class Workspace {
  history!:SceneHistory;selection=new Set<string>();editing=false;mode:'airport'|'facility'='facility';
  private session!:DesignSession;private staticGround!:StaticGround;private free?:FreeCamera;private freeMode=false;private exitDialog?:Promise<boolean>;
  private scene=new THREE.Scene();private groundScene=new THREE.Scene();private device=currentDevice();private renderSize='';private contextLost=false;private library!:GSELibrary;private camera=new THREE.PerspectiveCamera(42,1,.05,30000);private renderer?:THREE.WebGLRenderer;private orbit?:OrbitControls;private transform?:TransformControls;
  private cabView?:CabDrivingView;private cabExterior?:{id:string;position:THREE.Vector3;target:THREE.Vector3;free:boolean};
  private audio=new VehicleAudio();private cloud!:CloudPanel;private driving!:DrivingPanel;private vehicleRigs=new Map<string,VehicleRig>();private routeLine?:THREE.LineSegments;private routeDisplay:RouteDisplay={points:[]};private routeHandles!:RouteHandles;private facilityGates=new FacilityGates();private routePoints:[number,number][]=[];private saving=false;
  private night=false;private running=new Set<string>();private vehicleLights=new Map<string,VehicleLighting>();
  private skyLight=new THREE.HemisphereLight(0xe9f7ff,0x596552,2.5);private sunLight=new THREE.DirectionalLight(0xfff6e9,3);
  private inputCanvas?:HTMLCanvasElement;private openMenu:'nav'|'tools'|undefined;private airportOverview=false;private airportUpright=false;private viewportSize='';
  private pivot=new THREE.Group();private objects=new Map<string,THREE.Group>();private fingerprints=new Map<string,string>();private selectionBox=new THREE.Box3Helper(new THREE.Box3(),0xb7ff3c);
  private imagery=new Imagery();private plane=new MapPlane(this.imagery);private plan!:PlanMap;private stage!:HTMLElement;
  private active=true;private tool:string|undefined;private draft:[number,number][]=[];private drawingLine?:THREE.Line;
  private drag=false;private transformStart:{base:THREE.Vector3;entities:Entity[]} |undefined;
  private modelPromise?:Promise<GLTF>;private mixers=new Map<string,{mixer:THREE.AnimationMixer;actions:Map<string,THREE.AnimationAction>;open:Set<string>}>();
  private services!:AircraftServices;private photo!:PhotoGround;
  private flight=0;private storageWarning=false;private messageTimer=0;private dragStart?:[number,number];private clipboard:Entity[]=[];
  private l=(key:string)=>labels[key]?.[this.lang==='tr'?0:1]||key;
  private say=(tr:string,en:string)=>this.lang==='tr'?tr:en;
  constructor(private root:HTMLElement,private lang:Lang,private exit:(where:'world'|'turkey')=>void){}
  async init(authCallback?:AuthCallback){
    this.root.innerHTML=`<button class="ws-menu-toggle ws-nav-toggle" data-menu="nav" aria-controls="wsNavigation" aria-expanded="false" type="button">›</button><button class="ws-menu-toggle ws-tools-toggle" data-menu="tools" aria-controls="wsTools" aria-expanded="false" type="button">›</button><div class="ws-nav" id="wsNavigation" hidden><div class="ws-crumb"><span class="ws-dot"></span><strong>ADB / LTBJ</strong><small id="wsSource"></small></div><div class="ws-tabs">${['world','turkey','airport','facility','design'].map(k=>`<button data-nav="${k}" data-label="${k}"></button>`).join('')}</div></div>
    <div class="ws-savebar" hidden><span id="wsSaveState"></span><button data-action="save" data-label="save" class="ws-primary"></button><button data-action="discard" data-label="discard"></button><button data-action="finishEdit" data-label="finishEdit"></button></div><div class="ws-body"><aside class="ws-panel" hidden><button class="ws-close-editor" data-action="closePanel" data-label="closePanel"></button><div class="ws-section"><h3 data-label="add"></h3><div class="ws-row ws-categories"><button data-category="all">Tümü / All</button><button data-category="aircraft">Uçak / Aircraft</button><button data-category="vehicle">Araç / GSE</button><button data-category="structure">Tesis / Facility</button><button data-category="tree">Ağaç / Trees</button></div><select id="wsCatalog" aria-label="Nesne türü">${Object.entries(CATALOG).map(([k,v])=>`<option value="${k}">${this.lang==='tr'?v.tr:v.en}</option>`).join('')}</select><div class="ws-row"><button data-action="place" data-label="place"></button><button data-action="center" data-label="center"></button></div><div id="wsDrawing" hidden><button data-action="finish" data-label="finish"></button><button data-action="cancel" data-label="cancel"></button><small id="wsPointCount"></small></div></div>
    <div class="ws-section"><div class="ws-row ws-triple">${['translate','rotate','scale'].map(k=>`<button data-transform="${k}" data-label="${k}"></button>`).join('')}</div><div class="ws-row">${['undo','redo','copy','paste','duplicate','remove','ground'].map(k=>`<button data-action="${k}" data-label="${k}"></button>`).join('')}</div><div class="ws-nudge"><button data-nudge="0,-.5" aria-label="Kuzeye 0,5 m">↑</button><button data-nudge="-.5,0" aria-label="Batıya 0,5 m">←</button><span>0,5 m</span><button data-nudge=".5,0" aria-label="Doğuya 0,5 m">→</button><button data-nudge="0,.5" aria-label="Güneye 0,5 m">↓</button><button data-turn="-5" aria-label="Sola 5 derece">↶ 5°</button><button data-turn="5" aria-label="Sağa 5 derece">5° ↷</button></div></div>
    <details class="ws-section" open><summary data-label="selected"></summary><div id="wsEmpty"></div><form id="wsProperties" hidden><label><span data-label="name"></span><input name="name" maxlength="100"></label><div class="ws-row"><label>X (m)<input name="x" type="number" step="0.01" required></label><label>Z (m)<input name="z" type="number" step="0.01" required></label></div><div class="ws-row"><label><span data-label="height"></span><input name="y" type="number" step="0.01" min="0" required></label><label><span data-label="heading"></span><input name="heading" type="number" step="0.1" required></label><label><span data-label="size"></span><input name="scale" type="number" step="0.01" min="0.02" max="100" required></label><label><span data-label="color"></span><input name="color" type="color"></label></div><label id="wsFuelLevel" hidden><span data-label="fuelLitres"></span><input name="fuelLitres" type="number" min="0" max="38000" step="100"></label><div id="wsDimensions"><div class="ws-row"><label><span data-label="width"></span><input name="width" type="number" min="0.05" max="1000" step="0.05"></label><label><span data-label="length"></span><input name="length" type="number" min="0.05" max="1000" step="0.05"></label><label><span data-label="bodyHeight"></span><input name="bodyHeight" type="number" min="0.05" max="1000" step="0.05"></label></div><div class="ws-row"><label id="wsRadius"><span data-label="radius"></span><input name="radius" type="number" min="0.05" max="1000" step="0.05"></label><label id="wsThickness"><span data-label="thickness"></span><input name="thickness" type="number" min="0.02" max="10" step="0.01"></label></div><label id="wsDoor"><span data-label="door"></span><select name="doorSide"><option value="long" data-label="longSide"></option><option value="short" data-label="shortSide"></option></select></label></div><button type="submit" class="ws-primary" data-label="apply"></button></form></details>
    <div class="ws-section"><h3 data-label="objects"></h3><input id="wsSearch" aria-label="Nesne ara"><div id="wsObjectList"></div><input id="wsGroupName" maxlength="80"><div class="ws-row"><button data-action="group" data-label="group"></button><button data-action="ungroup" data-label="ungroup"></button></div></div><div class="ws-section ws-row"><button data-action="export" data-label="export"></button><button data-action="import" data-label="import"></button></div></aside>
    <div class="ws-map"><div class="ws-toolbar" id="wsTools" hidden><button data-view="3d">3D</button><button data-view="2d">2D</button><button data-action="free" data-label="free"></button><button data-action="top" data-label="top"></button><button data-action="focus" data-label="focus"></button><button data-action="vehicle" data-label="vehicle"></button><button data-action="services" data-label="services"></button><button data-action="library" data-label="library"></button><button data-action="photo" data-label="photo"></button><button data-action="night" aria-pressed="false">Gece modu</button><label class="ws-ground-choice"><span data-label="groundMode"></span><select id="wsGround" aria-label="Zemin / Ground"><option value="ortho" data-label="ortho"></option><option value="photo" data-label="photoGround"></option><option value="plan" data-label="plainGround"></option></select></label><button data-action="cloud" data-label="cloud"></button><button data-action="saveCamera" data-label="saveCamera"></button><button data-action="restoreCamera" data-label="restoreCamera"></button></div><div id="wsStage" tabindex="0"></div><div id="wsBoxSelect" hidden></div><div class="ws-move-pad" hidden><small id="wsPadLabel"></small><div><button data-pad="up" aria-label="İleri / Forward">↑</button><button data-pad="left" aria-label="Sola / Left">←</button><button data-pad="down" aria-label="Geri / Back">↓</button><button data-pad="right" aria-label="Sağa / Right">→</button><button data-pad="rise" aria-label="Yukarı / Rise">＋</button><button data-pad="lower" aria-label="Aşağı / Lower">−</button></div></div><div class="ws-zoom"><button data-action="zoomIn" aria-label="Yakınlaş / Zoom in">+</button><button data-action="zoomOut" aria-label="Uzaklaş / Zoom out">−</button></div><div id="wsFallback" hidden></div><div id="wsToast" role="status" aria-live="polite"></div><div class="ws-hud"><strong id="wsLocation"></strong><span id="wsSelection"></span><small id="wsMapStatus"></small></div><div class="ws-gate-controls" hidden><button data-action="facility-gate"></button></div><div class="ws-animations" hidden><button data-action="drive" data-label="drive"></button><button data-action="engine" aria-pressed="false">Aracı çalıştır</button><button data-animation="Platform_Raise_4s"></button><button data-animation="Tank_Railing_Raise"></button><button data-animation="Platform_Gate_Open"></button></div><div class="ws-credit">Tiles © Esri · Vantor · Earthstar Geographics · GIS User Community <a href="https://goto.arcgisonline.com/maps/World_Imagery" target="_blank" rel="noopener">Sources</a></div></div></div><input id="wsImportFile" type="file" accept=".json,application/json" hidden>`;
    const response=await fetch('/data/adb-legacy.json');if(!response.ok)throw new Error('ADB verisi alınamadı.');const source=importScene(await response.json());
    const data=source; // Local drafts are restored only after server-side designer authorization.
    if(data===source){const [x,z]=[16,20];const truck=newEntity('R14',x,z,this.lang);truck.heading=165;data.entities.push(truck);}
    this.history=new SceneHistory(data);this.session=new DesignSession(data);this.imagery.enabled=false;this.stage=this.$('#wsStage');this.stage.addEventListener('pointerdown',()=>{this.airportOverview=false;this.setMenu(undefined);});this.stage.addEventListener('wheel',()=>{this.airportOverview=false;},{passive:true});
    this.scene.background=null;this.scene.fog=new THREE.Fog('#94adb7',6500,12000);this.groundScene.add(this.plane.group);this.scene.add(this.pivot,this.selectionBox);this.selectionBox.visible=false;
    this.sunLight.position.set(-120,240,90);this.scene.add(this.skyLight,this.sunLight);
    const ground=new THREE.Mesh(new THREE.PlaneGeometry(3000,5100),new THREE.MeshBasicMaterial({color:'#56695c',depthTest:false,depthWrite:false}));ground.rotation.x=-Math.PI/2;ground.position.set(250,-.1,-1300);ground.renderOrder=-1000;this.groundScene.add(ground);
    this.staticGround=new StaticGround(()=>{this.tintGround();this.plan?.draw();if(this.history)this.updateGroundStatus();});this.groundScene.add(this.staticGround.group);
    this.plan=new PlanMap(this.stage,this.imagery,{running:()=>this.running,ground:()=>this.staticGround,boxSelect:(ids,extend)=>{if(!extend)this.selection.clear();ids.forEach(id=>this.selection.add(id));this.refreshSelection();},photo:()=>this.photo,markers:()=>this.services?.markers()||[],serviceClick:(x,z,t)=>this.services?.hit2D(x,z,t)||false,entities:()=>this.history.current.entities,selection:()=>this.selection,helpersVisible:()=>this.editing,cameraInput:()=>this.manualCamera(),editable:()=>this.editing&&!this.driving?.active,drawing:()=>!!this.tool||!!this.driving?.drawing,route:()=>this.routePoints,routeDisplay:()=>this.routeDisplay,gateAmount:id=>this.facilityGates.amount(id),drive:()=>this.driving?.active?{id:this.driving.vehicleId!,signal:this.driving.motion?.signal||'off'}:undefined,click:(x,z,hit,extend)=>this.clickMap(x,z,hit,extend,true),dragStart:()=>this.history.checkpoint(),drag:(dx,dz)=>{moveEntities(this.history.current,this.selection,dx,dz);this.syncObjects();},dragEnd:()=>this.changed(),change:()=>this.updateLocation()});
    this.services=new AircraftServices(this.$('.ws-map'),{entities:()=>this.history.current.entities,object:id=>this.objects.get(id),select:id=>{this.selection=new Set([id]);this.refreshSelection();this.action('focus');},focus:(target,offset)=>{this.plan.view([target.x,target.z],22);this.flyTo(target,offset.length(),true,false,offset);},redraw:()=>this.plan.draw(),realScale:id=>{this.history.change(d=>{const o=d.entities.find(o=>o.id===id);if(o)o.scale=1;});this.changed();this.refreshSelection();}});
    this.photo=new PhotoGround(this.$('.ws-map'),()=>({...validatePhoto(this.history.current.groundPhoto),enabled:['photo','overlay'].includes(this.groundMode())}),p=>{if(!this.setEditing(true))return;this.history.change(d=>{d.groundPhoto=p;d.sharedGround=p.enabled?'photo':'ortho';});this.changed();},()=>{this.tintGround();this.plan.draw();},p=>this.focusPhoto(p));this.groundScene.add(this.photo.group);
    this.library=new GSELibrary(this.$('.ws-map'),(preset,center)=>{if(!this.setEditing(true))return;this.$<HTMLSelectElement>('#wsCatalog').value=preset;this.action(center?'center':'place');this.collapseEditor();if(center)this.action('focus');});
    this.cloud=new CloudPanel(this.$('.ws-map'),()=>this.history.current,data=>{this.driving?.close();this.history.checkpoint();this.history.current=validateScene(data);this.session=new DesignSession(this.history.current);this.selection.clear();this.changed();},text=>this.notify(text),()=>{if(!this.cloud?.canEdit&&this.editing)this.setEditing(false);this.driving?.refreshMode();this.updateSaveState();});
    this.driving=new DrivingPanel(this.$('.ws-map'),{
      cabin:on=>this.setCabin(on),entities:()=>this.history.current.entities,routes:()=>this.history.current.routes||[],
      driveStates:()=>this.history.current.driving||[],
      retainDrive:(id,state)=>{const states=(this.history.current.driving||[]).filter(s=>s.vehicleId!==id);if(state)states.push(state);if(states.length)this.history.current.driving=states;else delete this.history.current.driving;},
      save:()=>{void this.save();},canSave:()=>this.cloud.canEdit,canDesign:()=>this.editing&&this.cloud.canEdit,enterDesign:()=>this.setEditing(true,true),audio:this.audio,
      saveRoute:route=>{this.history.change(d=>{d.routes??=[];const index=d.routes.findIndex(r=>r.id===route.id);if(index<0)d.routes.push(route);else d.routes[index]=route;});this.updateSaveState();},
      removeRoute:id=>{this.history.change(d=>{d.routes=(d.routes||[]).filter(r=>r.id!==id);d.driving=(d.driving||[]).filter(s=>s.routeId!==id);});this.changed();},
      checkpoint:()=>this.history.checkpoint(),changed:()=>this.changed(),running:id=>this.running.has(id),
      engine:(id,on)=>{this.audio.engine(id,on);on?this.running.add(id):this.running.delete(id);this.updateAnimationButtons();},
      blocked:id=>{const pack=this.mixers.get(id);return !!pack&&([...pack.open].length>0||[...pack.actions.values()].some(a=>a.time>.02));},
      wheelbase:id=>{const e=this.history.current.entities.find(e=>e.id===id);return refuellerDimensions(e?.preset||'R14',e?.length,e?.scale).wheelbase;},
      articulation:id=>{const e=this.history.current.entities.find(e=>e.id===id);return refuellerDimensions(e?.preset||'R14',e?.length,e?.scale);},
      move:(id,m,follow)=>{const e=this.history.current.entities.find(e=>e.id===id);if(!e)return;const dx=m.pose.x-e.position[0],dz=m.pose.z-e.position[2];e.position[0]=m.pose.x;e.position[2]=m.pose.z;e.heading=m.pose.heading*180/Math.PI;e.trailerAngle=m.trailerAngle;this.vehicleRigs.get(id)?.setArticulation(m.trailerAngle);const g=this.objects.get(id);if(g)applyTransform(g,e);if(follow&&!this.cabView?.active){this.flight++;this.camera.position.x+=dx;this.camera.position.z+=dz;if(this.orbit){this.orbit.target.x+=dx;this.orbit.target.z+=dz;}this.plan.center[0]+=dx;this.plan.center[1]+=dz;}this.plan.draw();},
      gateWaiting:(e,m)=>this.facilityGates.waiting(e,m.pose,m.speed,m.speed<-.01||m.throttle<0,this.history.current.entities)?.id,
      openGate:id=>{const e=this.history.current.entities.find(e=>e.id===id),gate=e&&this.facilityGates.nearest(e,this.history.current.entities);if(gate){this.history.change(()=>{gate.gateOpen=true;});this.changed();this.notify(this.say('Tesis kapısı açılıyor.','Facility gate opening.'));}else this.notify(this.say('Yakında tesis kapısı yok.','No facility gate nearby.'));},
      path:display=>this.drawRoute(display),
      notify:text=>this.notify(text),focus:()=>{this.airportOverview=false;if(this.freeMode)this.setFree(false);this.collapseEditor();this.action('focus');this.updateSelectionBox();this.updatePad();}
    });
    this.routeHandles=new RouteHandles(this.stage,{
      project:([x,z])=>{if(this.plan.enabled)return this.plan.toScreen(x,z);const p=new THREE.Vector3(x,.15,z).project(this.camera);return p.z<-1||p.z>1?undefined:[(p.x+1)*this.stage.clientWidth/2,(1-p.y)*this.stage.clientHeight/2];},
      world:(x,y)=>{if(this.plan.enabled)return this.plan.toWorld(x,y);const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(x/this.stage.clientWidth*2-1,1-y/this.stage.clientHeight*2),this.camera);const p=ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),new THREE.Vector3());return p?[p.x,p.z]:undefined;},
      begin:i=>this.driving.beginPointDrag(i),move:(i,x,z)=>this.driving.movePoint(i,x,z),end:cancel=>this.driving.endPointDrag(cancel),
      lock:on=>{this.flight++;if(this.orbit)this.orbit.enabled=!on&&!this.freeMode;if(this.free)this.free.paused=on;}
    });
    this.setView(this.device.initialView);
    this.imagery.onChange=()=>{this.plane.sync();this.plan.draw();this.updateGroundStatus();};
    this.bind();this.setLanguage(this.lang);this.syncObjects();new ResizeObserver(()=>this.resize()).observe(this.stage);this.resize();window.addEventListener('resize',()=>this.resize());document.addEventListener('fullscreenchange',()=>this.resize());screen.orientation?.addEventListener('change',()=>this.resize());
    const clock=new THREE.Clock();let lastFrame=0;const frame=(now=0)=>{requestAnimationFrame(frame);if(this.device.mobile&&now-lastFrame<32)return;lastFrame=now;const dt=Math.min(.1,clock.getDelta());if(!this.active||document.hidden)return;let gatesChanged=false;advanceSimulation(dt,this.driving?.rate||1,(step,last)=>{gatesChanged=this.facilityGates.update(step,this.history.current.entities,this.running,id=>this.objects.get(id))||gatesChanged;this.driving?.tick(step,last);});const audible=this.driving?.vehicleId||this.selected()[0]?.id,motion=audible===this.driving?.vehicleId?this.driving.motion:undefined;this.audio.update(dt,{id:audible,running:!!audible&&this.running.has(audible),speed:motion?.speed||0,throttle:motion?.throttle||0,braking:motion?.braking||false,automatic:motion?.mode==='route',cabin:this.cabView?.active,distance:audible&&this.objects.get(audible)?this.camera.position.distanceTo(this.objects.get(audible)!.position):0,signal:motion?.signal,horn:this.driving?.horn});for(const {mixer} of this.mixers.values())mixer.update(dt);for(const [id,rig] of this.vehicleLights){const m=this.driving?.vehicleId===id?this.driving.motion:undefined;rig.update(this.running.has(id),this.night,now,m?.signal,m?.braking,(m?.speed||0)<0);if(m)this.vehicleRigs.get(id)?.update(m.distance,m.steer,m.trailerAngle);}if(this.driving?.active||gatesChanged)this.plan.draw();this.render3D(now,dt);this.routeHandles?.update();};frame();
    document.addEventListener('visibilitychange',()=>{if(document.hidden)this.audio.silence();});window.addEventListener('pagehide',()=>this.audio.silence());
    await this.cloud.init(authCallback);
    if(this.storageWarning)this.notify(this.say('Yerel kayıt okunamadı; kaynak sahne açıldı.','Local save could not be read; source scene opened.'));
  }
  private setCabin(inside:boolean){
    if(!inside){
      if(!this.cabView?.active)return true;
      const saved=this.cabExterior;this.cabView.exit();this.cabExterior=undefined;this.root.classList.remove('cab-driving');
      this.flight++;
      if(saved){const e=this.history.current.entities.find(e=>e.id===saved.id),origin=new THREE.Vector3().fromArray(e?.position||[0,0,0]);this.camera.position.copy(origin).add(saved.position);this.orbit?.target.copy(origin).add(saved.target);this.freeMode=saved.free;}
      if(this.orbit){this.orbit.enabled=!this.freeMode;this.orbit.enableDamping=false;this.orbit.update();this.orbit.enableDamping=true;}
      if(this.free){this.free.enabled=this.freeMode;this.free.paused=false;this.free.clear();this.free.sync();}
      this.drawRoute(this.routeDisplay);this.updateSelectionBox();this.updatePad();return true;
    }
    const e=this.history.current.entities.find(e=>e.id===this.driving?.vehicleId);if(!e||!this.driving.active||this.driving.drawing)return false;
    if(this.plan.enabled)this.setView('3d');
    const cab=this.vehicleRigs.get(e.id)?.cab;if(this.plan.enabled||!this.cabView||!cab){this.notify(this.say('Kabin için 3D araç modelinin yüklenmesini bekleyin.','Wait for the 3D vehicle model to load before entering the cab.'));return false;}
    this.flight++;this.airportOverview=false;this.setMenu(undefined);
    const origin=new THREE.Vector3().fromArray(e.position);this.cabExterior={id:e.id,position:this.camera.position.clone().sub(origin),target:(this.freeMode?this.camera.position.clone().addScaledVector(this.camera.getWorldDirection(new THREE.Vector3()),30):(this.orbit?.target.clone()||origin.clone())).sub(origin),free:this.freeMode};
    if(this.orbit){this.orbit.enableDamping=false;this.orbit.update();this.orbit.enableDamping=true;this.orbit.enabled=false;}
    if(this.free){this.free.enabled=false;this.free.paused=true;this.free.clear();}
    this.cabView.enter(cab);this.root.classList.add('cab-driving');this.selectionBox.visible=false;if(this.routeLine)this.routeLine.visible=false;this.routeHandles?.set({points:[]});this.updatePad();return true;
  }
  private render3D(now:number,dt:number){
    if(this.plan.enabled||!this.renderer)return;
    const m=this.driving?.motion;
    if(this.cabView?.active&&m){
      this.cabView.update({speed:m.speed,steer:m.steer,rpm:this.audio.tone.rpm,gear:this.audio.tone.gear,running:this.running.has(this.driving.vehicleId!),night:this.night,signal:m.signal,rate:this.driving.rate},now);
      this.cabView.renderViews(this.renderer,this.groundScene,this.scene,now);
    }else{
      if(this.freeMode)this.free?.update(dt);else if(!this.routeHandles?.dragging)this.orbit?.update();this.constrainCamera();
      if(m)this.vehicleRigs.get(this.driving.vehicleId!)?.cab.update({speed:m.speed,steer:m.steer,rpm:this.audio.tone.rpm,gear:this.audio.tone.gear,running:this.running.has(this.driving.vehicleId!),night:this.night});
    }
    this.updateSelectionBox();this.renderer.clear();this.renderer.render(this.groundScene,this.camera);this.renderer.clearDepth();this.renderer.render(this.scene,this.camera);this.cabView?.renderOverlay(this.renderer);
  }
  private ensure3D(){
    if(this.renderer)return !this.contextLost;
    try{
      this.renderer=new THREE.WebGLRenderer({antialias:!this.device.mobile,powerPreference:this.device.mobile?'low-power':'high-performance',logarithmicDepthBuffer:true});this.renderer.setPixelRatio(this.device.pixelRatio);this.renderer.autoClear=false;this.renderer.setClearColor(this.night?'#07111e':'#94adb7');this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;this.renderer.domElement.className='world-canvas';this.renderer.domElement.setAttribute('aria-label','ADB 3D sahne');this.stage.appendChild(this.renderer.domElement);this.inputCanvas=portraitInput(this.renderer.domElement);
      this.orbit=new OrbitControls(this.camera,this.inputCanvas);configureWorkspaceOrbit(this.orbit);
      this.orbit.addEventListener('start',()=>this.manualCamera());this.orbit.addEventListener('end',()=>{this.updateTiles();this.updateLocation();});
      this.transform=new TransformControls(this.camera,this.inputCanvas);this.transform.setSize(.8);this.transform.showY=false;this.scene.add(this.transform.getHelper());this.transform.enabled=false;
      this.transform.addEventListener('mouseDown',()=>this.beginTransform());this.transform.addEventListener('objectChange',()=>this.applyGizmo());this.transform.addEventListener('mouseUp',()=>{if(this.drag){this.drag=false;if(this.orbit)this.orbit.enabled=!this.freeMode;if(this.free)this.free.paused=false;this.changed();}});
      this.cabView=new CabDrivingView(this.camera,this.inputCanvas,this.stage,this.device.mobile,{key:(k,down)=>{this.driving?.key(k,down);},exit:()=>{this.driving?.setCabin(false);}});this.cabView.setLanguage(this.lang);
      const pointers3D=new Set<number>();let multi3D=false,moved3D=false;
      this.inputCanvas.addEventListener('pointerdown',e=>{pointers3D.add(e.pointerId);if(pointers3D.size>1)multi3D=true;else moved3D=false;this.dragStart=[e.clientX,e.clientY];});
      this.inputCanvas.addEventListener('pointermove',e=>{if(this.dragStart&&pointers3D.has(e.pointerId)&&Math.hypot(e.clientX-this.dragStart[0],e.clientY-this.dragStart[1])>4)moved3D=true;});
      this.inputCanvas.addEventListener('pointercancel',e=>{pointers3D.delete(e.pointerId);if(!pointers3D.size)multi3D=false;this.dragStart=undefined;});
      this.inputCanvas.addEventListener('pointerup',e=>{const wasMulti=multi3D;pointers3D.delete(e.pointerId);if(!pointers3D.size)multi3D=false;if(wasMulti||moved3D||this.cabView?.active)return;if(e.button!==0||this.transform?.axis||!this.dragStart||Math.hypot(e.clientX-this.dragStart[0],e.clientY-this.dragStart[1])>4)return;const r=this.inputCanvas!.getBoundingClientRect();const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2),this.camera);const p=ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),new THREE.Vector3());const hits=ray.intersectObjects([...this.objects.values()],true);const marker=hits.find(h=>h.object.userData.servicePointId);if(marker&&!this.tool&&!this.driving?.drawing){this.services.focus(marker.object.userData.servicePointId);return;}let hit:THREE.Object3D|undefined=hits[0]?.object;while(hit&&!hit.userData.entityId)hit=hit.parent||undefined;const point=!this.editing&&!this.driving?.drawing&&hit?hits[0].point:p;if(point)this.clickMap(point.x,point.z,hit?.userData.entityId,e.ctrlKey||e.metaKey,true);});
      this.inputCanvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.contextLost=true;this.setView('2d');this.$<HTMLButtonElement>('[data-view="3d"]').disabled=true;this.notify(this.say('Grafik bağlantısı kesildi; sahneniz korunarak 2D açıldı.','Graphics context lost; your scene is preserved in 2D.'));});
      this.inputCanvas.addEventListener('webglcontextrestored',()=>{this.contextLost=false;this.$<HTMLButtonElement>('[data-view="3d"]').disabled=false;this.notify(this.say('3D yeniden hazır. 3D düğmesiyle açabilirsiniz.','3D is ready again. Use the 3D button to return.'));});
      this.free=new FreeCamera(this.camera,this.inputCanvas,()=>{this.manualCamera();this.updateLocation();});this.bind3DEditing();this.syncObjects();return true;
    }catch(e){console.warn('ADB 2D fallback',e);this.renderer?.domElement.remove();this.renderer?.dispose();this.renderer=undefined;this.$<HTMLButtonElement>('[data-view="3d"]').disabled=true;this.$('#wsFallback').hidden=false;return false;}
  }
  private $<T extends HTMLElement=HTMLElement>(s:string){return this.root.querySelector<T>(s)!;}
  private setMenu(menu:'nav'|'tools'|undefined){
    this.openMenu=menu;this.$('#wsNavigation').hidden=menu!=='nav';this.$('#wsTools').hidden=menu!=='tools';
    this.root.querySelectorAll<HTMLButtonElement>('[data-menu]').forEach(b=>{const open=b.dataset.menu===menu;b.setAttribute('aria-expanded',String(open));b.textContent=open?'⌄':'›';const name=b.dataset.menu==='nav'?this.say('Gezinme menüsü','Navigation menu'):this.say('Görünüm ve araçlar','View and tools');b.title=name;b.setAttribute('aria-label',`${name} · ${open?this.say('kapat','close'):this.say('aç','open')}`);});
  }
  private bind(){
    this.root.querySelectorAll<HTMLButtonElement>('[data-menu]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const menu=b.dataset.menu as 'nav'|'tools';this.setMenu(this.openMenu===menu?undefined:menu);});
    this.root.addEventListener('keydown',e=>{if(e.key==='Escape')this.setMenu(undefined);});
   this.root.querySelectorAll<HTMLButtonElement>('[data-nav]').forEach(b=>b.onclick=()=>{this.setMenu(undefined);const n=b.dataset.nav!;if(n==='world'||n==='turkey'){void this.requestLeave().then(ok=>{if(ok)this.exit(n);});return;}if(n==='design'){if(this.editing&&this.$('.ws-panel').hidden){this.$('.ws-panel').hidden=false;this.resize();}else if(this.editing)void this.requestLeave();else this.setEditing(true);}else{this.navigate(n as 'airport'|'facility');}});
    this.root.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.onclick=()=>this.setView(b.dataset.view as '2d'|'3d'));
    this.root.querySelectorAll<HTMLButtonElement>('[data-transform]').forEach(b=>b.onclick=()=>this.setTransform(b.dataset.transform as 'translate'|'rotate'|'scale'));
    this.root.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(b=>b.onclick=()=>this.action(b.dataset.action!));
    this.root.querySelectorAll<HTMLButtonElement>('[data-nudge]').forEach(b=>b.onclick=()=>{if(!this.editing||!this.selection.size)return;const [x,z]=b.dataset.nudge!.split(',').map(Number);this.change(d=>moveEntities(d,this.selection,x,z));});
    this.root.querySelectorAll<HTMLButtonElement>('[data-turn]').forEach(b=>b.onclick=()=>{if(this.editing)this.change(d=>d.entities.filter(o=>this.selection.has(o.id)).forEach(o=>o.heading+=Number(b.dataset.turn)));});
    this.root.querySelectorAll<HTMLButtonElement>('[data-animation]').forEach(b=>b.onclick=()=>this.animate(b.dataset.animation!));
    this.$<HTMLSelectElement>('#wsGround').onchange=()=>{if(!this.setEditing(true))return;this.history.change(d=>{d.sharedGround=this.$<HTMLSelectElement>('#wsGround').value as GroundMode;});this.changed();};
    this.root.querySelectorAll<HTMLButtonElement>('[data-category]').forEach(b=>b.onclick=()=>{const category=b.dataset.category;this.root.querySelectorAll('[data-category]').forEach(a=>a.classList.toggle('active',a===b));const select=this.$<HTMLSelectElement>('#wsCatalog');for(const o of select.options)o.hidden=category!=='all'&&(category==='structure'?!['structure','ground','tank','wall'].includes(CATALOG[o.value].kind):CATALOG[o.value].kind!==category);if(select.selectedOptions[0].hidden)select.value=Array.from(select.options).find(o=>!o.hidden)!.value;});
    this.bindPad();
    window.addEventListener('beforeunload',e=>{if(this.session.dirty(this.history.current)){e.preventDefault();e.returnValue='';}});
    this.$<HTMLInputElement>('#wsSearch').oninput=()=>this.renderList();
    this.$<HTMLFormElement>('#wsProperties').onsubmit=e=>{e.preventDefault();if(!this.editing||this.selection.size!==1)return;const f=new FormData(this.$<HTMLFormElement>('#wsProperties'));const values=['x','y','z','heading','scale'].map(k=>Number(f.get(k)));if(values.some(n=>!Number.isFinite(n))||values.slice(0,3).some(n=>Math.abs(n)>50000))return;this.change(d=>{const o=d.entities.find(o=>this.selection.has(o.id))!;o.name=String(f.get('name')).slice(0,100);o.position=[values[0],Math.max(0,values[1]),values[2]];o.heading=values[3];o.scale=Math.max(.02,Math.min(100,values[4]));o.color=String(f.get('color'));if(o.preset==='R14'){const fuel=Number(f.get('fuelLitres'));if(Number.isFinite(fuel))o.fuelLitres=Math.max(0,Math.min(38000,fuel));}if(!['aircraft','vehicle'].includes(o.kind)){for(const [field,key] of [['width','width'],['length','length'],['bodyHeight','height'],['radius','radius'],['thickness','thickness']] as const){const value=Number(f.get(field));if(Number.isFinite(value)&&value>=.02&&value<=1000)o[key]=value;}o.doorSide=String(f.get('doorSide'))==='short'?'short':'long';}});};
    this.$<HTMLInputElement>('#wsImportFile').onchange=async()=>{const input=this.$<HTMLInputElement>('#wsImportFile'),file=input.files?.[0];if(!file)return;try{if(file.size>12_000_000)throw new Error(this.say('Dosya en fazla 12 MB olabilir.','File must be under 12 MB.'));const data=importScene(JSON.parse(await file.text()));this.history.checkpoint();this.history.current=data;this.selection.clear();this.changed();this.notify(this.say(`${data.entities.length} nesne içe alındı. Geri Al ile önceki sahneye dönebilirsin.`,`${data.entities.length} objects imported. Undo restores the previous scene.`));}catch(e){this.notify(String(e));}input.value='';};
    window.addEventListener('keydown',e=>{if(!this.active||(e.target as HTMLElement).closest('input,textarea,select,[contenteditable]'))return;const mod=e.ctrlKey||e.metaKey,k=e.key.toLowerCase();if(!mod&&this.driving?.key(k,true)){e.preventDefault();return;}if(this.freeMode&&!this.plan.enabled&&!mod&&['w','a','s','d','q','e','shift'].includes(k)){e.preventDefault();this.flight++;this.free?.key(k,true);return;}if(!this.editing)return;if(!mod&&k.startsWith('arrow')&&this.selection.size){e.preventDefault();const step=e.shiftKey?5:.5;this.change(d=>moveEntities(d,this.selection,k==='arrowleft'?-step:k==='arrowright'?step:0,k==='arrowup'?-step:k==='arrowdown'?step:0));return;}if(mod&&k==='s'){e.preventDefault();this.save();return;}if(mod&&k==='z'){e.preventDefault();this.action(e.shiftKey?'redo':'undo');}else if(mod&&k==='y'){e.preventDefault();this.action('redo');}else if(mod&&k==='c'){e.preventDefault();this.clipboard=this.selected().map(o=>structuredClone(o));}else if(mod&&k==='v'){e.preventDefault();this.duplicate(this.clipboard);}else if(k==='delete'||k==='backspace'){e.preventDefault();this.action('remove');}else if(k==='escape')this.action('cancel');else if(k==='enter'&&this.tool)this.action('finish');else if(!mod&&['w','e','r'].includes(k))this.setTransform(({w:'translate',e:'rotate',r:'scale'} as const)[k as 'w']);});
    window.addEventListener('keyup',e=>{this.driving?.key(e.key.toLowerCase(),false);this.free?.key(e.key.toLowerCase(),false);});
  }
  setLanguage(lang:Lang){this.lang=lang;this.cabView?.setLanguage(lang);this.cloud?.setLanguage(lang);this.driving?.setLanguage(lang);this.setMenu(this.openMenu);this.services?.setLanguage(lang);this.photo?.setLanguage(lang);this.library?.setLanguage(lang);this.root.querySelectorAll<HTMLElement>('[data-label]').forEach(e=>e.textContent=this.l(e.dataset.label!));this.$<HTMLInputElement>('#wsSearch').placeholder=this.l('search');this.$<HTMLInputElement>('#wsGroupName').placeholder=this.l('groupName');this.$<HTMLSelectElement>('#wsCatalog').querySelectorAll('option').forEach(o=>o.textContent=lang==='tr'?CATALOG[o.value].tr:CATALOG[o.value].en);this.$('#wsFallback').textContent=this.say('WebGL kullanılamıyor. 2D harita ve tasarım araçları açık.','WebGL unavailable. 2D map and design tools are available.');this.renderList();this.renderProperties();this.updateLocation();this.updateAnimationButtons();this.updateSaveState();this.updatePad();this.imagery.onChange();}
  show(mode:'airport'|'facility',edit=false){this.active=true;this.root.hidden=false;this.setMenu(undefined);this.setView('3d');this.navigate(mode);this.setEditing(edit);requestAnimationFrame(()=>this.resize());}
  hide(){this.audio.silence();this.driving?.close();syncPortraitLock(false);this.free?.clear();this.active=false;this.root.hidden=true;this.flight++;}
  navigate(mode:'airport'|'facility',smooth=true){
    this.driving?.close();this.mode=mode;syncPortraitLock(this.active&&mode==='airport'&&this.device.mobile);this.applyGround();this.airportOverview=mode==='airport';this.airportUpright=this.device.mobile;
    if(this.freeMode)this.setFree(false);
    if(mode==='airport')this.frameAirport(smooth);
    else{this.plan.bearing=0;this.plan.view(FACILITY_CENTER,185);this.flyTo(new THREE.Vector3(FACILITY_CENTER[0],0,FACILITY_CENTER[1]),130,smooth);}
    this.root.querySelectorAll<HTMLElement>('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===mode||(b.dataset.nav==='design'&&this.editing)));this.updateLocation();
  }
  private frameAirport(smooth=false){
    const frame=airportFrame(this.stage.clientWidth,this.stage.clientHeight,this.airportUpright);
    this.plan.bearing=frame.bearing;this.plan.view([AIRPORT_TARGET.x,AIRPORT_TARGET.z],frame.span);
    this.flyTo(AIRPORT_TARGET,frame.distance,smooth,false,frame.offset);
  }

  private unlockDesign(){
    if(this.cloud?.canEdit)return true;
    this.notify(this.say('Kalıcı düzenleme için tasarımcı hesabınızla giriş yapın.','Sign in with your designer account to edit and save.'));this.cloud?.open();return false;
  }
  setEditing(enabled:boolean,keepDrive=false){if(enabled&&!this.unlockDesign())return false;if(enabled&&!keepDrive)this.driving?.close();this.editing=enabled;this.driving?.refreshMode();this.drawRoute(this.routeDisplay);if(enabled){this.library.element.hidden=true;this.photo.element.hidden=true;if(this.services.visible)this.services.toggle();}this.$('.ws-panel').hidden=!enabled;this.root.classList.toggle('editing',enabled);this.$('[data-nav="design"]').classList.toggle('active',enabled);this.cancelTool();this.updateSelectionBox();this.renderProperties();this.updateSaveState();this.updatePad();this.resize();return true;}
  private setView(view:'2d'|'3d'){
    if(view==='2d')this.driving?.setCabin(false);
    if(view==='3d'&&!this.ensure3D())view='2d';const was2d=this.plan.enabled;this.plan.enabled=view==='2d';this.plan.canvas.hidden=!this.plan.enabled;if(this.renderer)this.renderer.domElement.hidden=this.plan.enabled;
    if(this.plan.enabled&&this.orbit&&!was2d){this.free?.clear();this.plan.center=this.viewCenter();this.plan.bearing=this.orbit.getAzimuthalAngle();this.plan.span=Math.max(30,2*this.camera.position.distanceTo(this.orbit.target)*Math.tan(THREE.MathUtils.degToRad(this.camera.fov/2))*this.camera.aspect);}
    if(!this.plan.enabled&&was2d){const distance=this.plan.span/(2*Math.tan(THREE.MathUtils.degToRad(this.camera.fov/2))*Math.max(.2,this.stage.clientWidth/Math.max(1,this.stage.clientHeight)));this.flyTo(new THREE.Vector3(this.plan.center[0],0,this.plan.center[1]),distance,false,false,cameraOffset(distance,this.plan.bearing));}
    this.root.querySelectorAll<HTMLElement>('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));this.updateSelectionBox();this.plan.refresh();this.updatePad();this.resize();if(this.airportOverview)this.frameAirport();
  }
  private focusPhoto(p:ReturnType<typeof validatePhoto>){const angle=p.rotation*Math.PI/180,w=Math.abs(Math.cos(angle))*p.width+Math.abs(Math.sin(angle))*p.height,h=Math.abs(Math.sin(angle))*p.width+Math.abs(Math.cos(angle))*p.height,aspect=Math.max(.3,this.stage.clientWidth/Math.max(1,this.stage.clientHeight));this.plan.view([p.x,p.z],Math.max(w,h*aspect)*1.12);this.flyTo(new THREE.Vector3(p.x,0,p.z),Math.max(h,w/aspect)*.56/Math.tan(THREE.MathUtils.degToRad(this.camera.fov/2)),true,true);}
  private collapseEditor(){if(this.device.compact){this.$('.ws-panel').hidden=true;this.resize();}}
  private groundMode(){return this.history.current.sharedGround||'ortho';}
  private applyGround(){const mode=this.groundMode();this.$<HTMLSelectElement>('#wsGround').value=mode;this.imagery.enabled=false;this.staticGround.sync(mode==='ortho');this.photo?.sync();this.updateTiles();this.plan.refresh();this.$('.ws-credit').hidden=mode!=='ortho';this.updateGroundStatus();}
  private resize(){
    this.device=currentDevice();this.root.classList.toggle('compact-device',this.device.compact);this.root.classList.toggle('touch-device',this.device.mobile);
    const viewport=syncPortraitLock(this.active&&!this.root.hidden&&this.mode==='airport'&&this.device.mobile);if(!this.root.hidden)this.root.style.height=`${Math.max(180,viewport.height)}px`;
    const w=this.stage.clientWidth,h=this.stage.clientHeight,newSize=`${w}/${h}`,viewportChanged=newSize!==this.viewportSize;this.viewportSize=newSize;const key=`${w}/${h}/${this.device.pixelRatio}`;
    if(w&&h&&this.renderer&&key!==this.renderSize){this.renderSize=key;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setPixelRatio(this.device.pixelRatio);this.renderer.setSize(w,h,false);}if(w&&h&&viewportChanged&&this.airportOverview)this.frameAirport();this.plan.draw();
  }
  private updateTiles(){if(this.plan.enabled){this.imagery.update(...this.plan.center,this.plan.span);return;}if(this.orbit)this.imagery.update(this.orbit.target.x,this.orbit.target.z,this.camera.position.distanceTo(this.orbit.target)*1.5);}
  private flyTo(target:THREE.Vector3,distance:number,smooth=true,top=false,offset?:THREE.Vector3){
    if(!this.orbit)return;this.orbit.enableDamping=false;this.orbit.update();this.orbit.enableDamping=true;const start=this.camera.position.clone(),startTarget=this.orbit.target.clone(),end=target.clone().add(offset||(top?new THREE.Vector3(0,distance,.001):new THREE.Vector3(distance*.64,distance*.65,distance*.52)));const token=++this.flight,t=performance.now();if(this.free)this.free.paused=true;
    const step=(now:number)=>{if(token!==this.flight){if(this.free)this.free.paused=false;return;}const k=smooth?Math.min(1,(now-t)/850):1,q=1-(1-k)**3;this.camera.position.lerpVectors(start,end,q);this.orbit!.target.lerpVectors(startTarget,target,q);this.orbit!.update();this.constrainCamera();if(k<1)requestAnimationFrame(step);else{this.free?.sync();if(this.free)this.free.paused=false;this.updateTiles();}};requestAnimationFrame(step);
  }
  private constrainCamera(){if(!this.orbit||this.cabView?.active)return;this.orbit.target.y=Math.max(0,this.orbit.target.y);constrainCameraHeight(this.camera);if(!this.freeMode)this.camera.lookAt(this.orbit.target);this.free?.constrain();}
  private manualCamera(){if(this.cabView?.active)return;this.flight++;this.airportOverview=false;this.driving?.releaseFollow();}
  private goToPoint(x:number,z:number){
    if(!Number.isFinite(x)||!Number.isFinite(z))return;
    this.manualCamera();this.free?.clear();
    if(this.plan.enabled){this.plan.view([x,z],this.plan.span*.8);return;}
    if(!this.orbit)return;const center=this.viewCenter(),focus=new THREE.Vector3(center[0],this.freeMode?0:this.orbit.target.y,center[1]);
    const offset=clickApproachOffset(this.camera.position,focus);this.flyTo(new THREE.Vector3(x,0,z),offset.length(),true,false,offset);
  }
  private clickMap(x:number,z:number,hit:string|undefined,extend:boolean,fromCanvas=false){
    if(this.driving?.click(x,z))return;
    if(this.driving?.active){if(fromCanvas&&!extend)this.goToPoint(x,z);return;}
    if(this.tool&&this.editing){const c=CATALOG[this.tool];if(c.kind==='ground'||c.kind==='wall'){this.draft.push([x,z]);this.updateDraft();if(this.tool==='MAIN_GATE'&&this.draft.length===2)this.finishDrawing();}else{const o=newEntity(this.tool,x,z,this.lang);this.change(d=>{numberRefueller(d,o);d.entities.push(o);});this.selection=new Set([o.id]);this.cancelTool();this.refreshSelection();}return;}
    if(!extend)this.selection.clear();if(hit){if(extend&&this.selection.has(hit))this.selection.delete(hit);else this.selection.add(hit);}this.refreshSelection();if(fromCanvas&&!extend&&(!this.editing||!hit))this.goToPoint(x,z);
  }
  private selected(){return this.history.current.entities.filter(o=>this.selection.has(o.id));}
  private change(fn:(d:SceneHistory['current'])=>void){if(!this.editing)return;this.history.change(fn);this.changed();}
  private changed(){this.history.current.updatedAt=new Date().toISOString();this.applyGround();this.syncObjects();this.renderList();this.renderProperties();this.updateLocation();this.updateSaveState();this.updatePad();}
  private syncObjects(){
    const ids=new Set(this.history.current.entities.map(o=>o.id));
    for(const [key,g] of this.objects)if(!ids.has(key)){if(this.cabExterior?.id===key)this.driving?.setCabin(false);this.scene.remove(g);this.vehicleLights.get(key)?.dispose();this.vehicleLights.delete(key);this.vehicleRigs.get(key)?.dispose();this.vehicleRigs.delete(key);this.running.delete(key);disposeObject(g);this.objects.delete(key);this.fingerprints.delete(key);this.mixers.delete(key);this.selection.delete(key);}
    for(const o of this.history.current.entities){const fingerprint=JSON.stringify([o.kind,o.preset,o.color,o.width,o.length,o.height,o.radius,o.thickness,o.points,o.wallStyle,o.flag,o.doorSide]);let g=this.objects.get(o.id);
      if(!g||this.fingerprints.get(o.id)!==fingerprint){if(this.cabExterior?.id===o.id)this.driving?.setCabin(false);if(g){this.scene.remove(g);this.vehicleLights.get(o.id)?.dispose();this.vehicleLights.delete(o.id);this.vehicleRigs.get(o.id)?.dispose();this.vehicleRigs.delete(o.id);disposeObject(g);this.mixers.delete(o.id);}g=makeObject(o);this.scene.add(g);this.objects.set(o.id,g);this.fingerprints.set(o.id,fingerprint);}
      if(this.renderer&&isRefueller(o.preset)&&g.userData.modelPending&&!g.userData.modelLoading){g.userData.modelLoading=true;void this.loadR14(o,g);}
      applyTransform(g,o);if(isFacilityGate(o))setGateOpening(g,this.facilityGates.amount(o.id));this.vehicleRigs.get(o.id)?.setArticulation(o.trailerAngle);this.vehicleRigs.get(o.id)?.setFuelLevel(o.fuelLitres);
    }
    this.services?.sync();this.photo?.sync();this.updateSelectionBox();this.plan.draw();
  }
  private drawRoute(display:RouteDisplay){
    this.routeDisplay=display;this.routePoints=display.points;this.routeHandles?.set(this.editing&&!this.cabView?.active?display:{points:[]});
    if(this.routeLine){this.routeLine.removeFromParent();this.routeLine.geometry.dispose();(this.routeLine.material as THREE.Material).dispose();this.routeLine=undefined;}
    if(display.points.length>1){
      const positions:number[]=[],colors:number[]=[],good=new THREE.Color('#57f7e5'),bad=new THREE.Color('#ff534c');
      for(let i=1;i<display.points.length;i++){const c=display.danger?.[i]||display.danger?.[i-1]?bad:good;for(const p of [display.points[i-1],display.points[i]]){positions.push(p[0],.12,p[1]);colors.push(c.r,c.g,c.b);}}
      const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geometry.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));
      this.routeLine=new THREE.LineSegments(geometry,new THREE.LineBasicMaterial({vertexColors:true,depthTest:false}));this.routeLine.visible=this.editing&&!this.cabView?.active;this.routeLine.renderOrder=1001;this.scene.add(this.routeLine);
    }
    this.plan.draw();
  }
  private async loadR14(o:Entity,root:THREE.Group){
    try{
      this.modelPromise??=new GLTFLoader().loadAsync('/models/refueller-38k-r14.glb');const gltf=await this.modelPromise;if(this.objects.get(o.id)!==root)return;
      const model=cloneModel(gltf.scene),pack=closedAnimationPack(model,gltf.animations),rig=new VehicleRig(model,o.preset!=='R14_2000'),bounds=new THREE.Box3().setFromObject(model),s=o.length/R14.length;
      // Ground and center the asset inside a stable selectable wrapper.
      model.scale.setScalar(s);model.position.set(-R14.centreX*s,-bounds.min.y*s,-R14.centreZ*s);
      const orient=new THREE.Group();orient.add(model);orient.rotation.y=-Math.PI/2;
      disposeObject(root);root.clear();root.add(orient);root.userData.modelPending=false;model.traverse(n=>{if(n instanceof THREE.Mesh)n.userData.sharedAsset=true;});
      this.mixers.set(o.id,pack);this.vehicleRigs.set(o.id,rig);this.vehicleLights.set(o.id,new VehicleLighting(model,this.groundScene));rig.setArticulation(this.history.current.entities.find(e=>e.id===o.id)?.trailerAngle);rig.setFuelLevel(this.history.current.entities.find(e=>e.id===o.id)?.fuelLitres);this.vehicleLights.get(o.id)!.update(this.running.has(o.id),this.night,performance.now());this.updateSelectionBox();this.updateAnimationButtons();
    }catch(e){this.modelPromise=undefined;root.userData.modelError=true;root.userData.modelLoading=false;this.notify(this.say('İkmal aracı modeli yüklenemedi. Bağlantıyı kontrol ederek sayfayı yenileyin.','Refueller model could not load. Check your connection and reload.'));console.warn(e);}
  }
  private refreshSelection(){this.services.selection(this.selected().length===1?this.selected()[0]:undefined);this.updateSelectionBox();this.renderList();this.renderProperties();this.updateLocation();this.updateAnimationButtons();this.updatePad();this.plan.draw();}
  private updateSelectionBox(){
    const list=this.selected();this.selectionBox.visible=this.editing&&!this.cabView?.active&&list.length>0&&!this.plan.enabled;this.selectionBox.box.makeEmpty();for(const o of list){const g=this.objects.get(o.id);if(g){g.updateMatrixWorld(true);this.selectionBox.box.union(new THREE.Box3().setFromObject(g));}}
    if(this.transform&&!this.drag){if(this.editing&&!this.driving?.active&&list.length&&!this.plan.enabled){const center=new THREE.Vector3();list.forEach(o=>center.add(new THREE.Vector3().fromArray(o.position)));center.divideScalar(list.length);this.pivot.position.copy(center);this.pivot.rotation.set(0,0,0);this.pivot.scale.setScalar(1);this.transform.attach(this.pivot);this.transform.enabled=true;}else{this.transform.detach();this.transform.enabled=false;}}
  }
  private setTransform(mode:'translate'|'rotate'|'scale'){if(this.transform){this.transform.setMode(mode);this.transform.showX=mode!=='rotate';this.transform.showY=mode==='rotate';this.transform.showZ=mode!=='rotate';}this.root.querySelectorAll<HTMLElement>('[data-transform]').forEach(b=>b.classList.toggle('active',b.dataset.transform===mode));}
  private beginTransform(){if(!this.editing)return;this.drag=true;this.flight++;if(this.orbit)this.orbit.enabled=false;if(this.free)this.free.paused=true;this.history.checkpoint();this.transformStart={base:this.pivot.position.clone(),entities:structuredClone(this.selected())};}
  private applyGizmo(){
    if(!this.drag||!this.transformStart)return;const {base,entities}=this.transformStart,delta=this.pivot.position.clone().sub(base),rot=this.pivot.rotation.y,factor=Math.max(.02,this.pivot.scale.x!==1?this.pivot.scale.x:this.pivot.scale.z),c=Math.cos(rot),s=Math.sin(rot);
    for(const original of entities){const o=this.history.current.entities.find(o=>o.id===original.id)!;const x=(original.position[0]-base.x)*factor,z=(original.position[2]-base.z)*factor;o.position=[base.x+c*x+s*z+delta.x,Math.max(0,base.y+(original.position[1]-base.y)*factor+delta.y),base.z-s*x+c*z+delta.z];o.heading=original.heading-THREE.MathUtils.radToDeg(rot);o.scale=Math.max(.02,Math.min(100,original.scale*factor));}
    this.syncObjects();
  }
  private renderList(){
    if(!this.history)return;const q=this.$<HTMLInputElement>('#wsSearch').value.toLocaleLowerCase(),data=this.history.current;const openGroups=new Set(Array.from(this.$('#wsObjectList').querySelectorAll<HTMLElement>('details[open]')).map(e=>e.dataset.groupSection));
    const row=(o:Entity)=>`<button class="ws-object ${this.selection.has(o.id)?'selected':''}" data-object="${esc(o.id)}"><i style="background:${o.color}"></i><span>${esc(o.name)}</span><small>${o.preset}</small></button>`;
    const match=(o:Entity)=>!q||`${o.name} ${o.preset}`.toLocaleLowerCase().includes(q);
    this.$('#wsObjectList').innerHTML=data.groups.map(g=>{const objs=data.entities.filter(o=>o.groupId===g.id&&match(o));if(!objs.length)return '';return `<details data-group-section="${esc(g.id)}" ${q||openGroups.has(g.id)||objs.some(o=>this.selection.has(o.id))?'open':''}><summary><button data-group="${esc(g.id)}">${esc(g.name)} <small>${objs.length}</small></button></summary>${objs.map(row).join('')}</details>`;}).join('')+data.entities.filter(o=>(!o.groupId||!data.groups.some(g=>g.id===o.groupId))&&match(o)).map(row).join('');
    this.$('#wsObjectList').querySelectorAll<HTMLButtonElement>('[data-object]').forEach(b=>b.onclick=e=>{this.cancelTool();this.clickMap(0,0,b.dataset.object,((e as MouseEvent).ctrlKey||(e as MouseEvent).metaKey));});
    this.$('#wsObjectList').querySelectorAll<HTMLButtonElement>('[data-group]').forEach(b=>b.onclick=e=>{e.preventDefault();this.cancelTool();if(!((e as MouseEvent).ctrlKey||(e as MouseEvent).metaKey))this.selection.clear();data.entities.filter(o=>o.groupId===b.dataset.group).forEach(o=>this.selection.add(o.id));this.refreshSelection();});
    this.$('#wsSource').title=data.source;this.$('#wsSource').textContent=`${data.entities.length} ${this.say('nesne','objects')} · ${this.storageWarning?this.say('Kayıt uyarısı','Save warning'):this.session.dirty(data)?this.say('Kaydedilmemiş değişiklik','Unsaved changes'):this.say('Bu tarayıcıdaki sahne','Scene in this browser')}`;
  }
  private renderProperties(){
    if(!this.history)return;const list=this.selected(),form=this.$<HTMLFormElement>('#wsProperties');form.hidden=list.length!==1;this.$('#wsEmpty').hidden=list.length===1;this.$('#wsEmpty').textContent=list.length?this.say(`${list.length} nesne seçili. Taşıma ve gruplama birlikte uygulanır.`,`${list.length} objects selected. Move and group them together.`):this.say('Haritadan veya listeden bir nesne seçin.','Select an object on the map or in the list.');
    if(list.length===1){const o=list[0];const values={name:o.name,fuelLitres:String(o.fuelLitres||0),x:o.position[0].toFixed(2),y:o.position[1].toFixed(2),z:o.position[2].toFixed(2),heading:o.heading.toFixed(1),scale:o.scale.toFixed(2),color:o.color,width:String(o.width),length:String(o.length),bodyHeight:String(o.height),radius:String(o.radius),thickness:String(o.thickness),doorSide:o.doorSide==='short'?'short':'long'};this.$('#wsFuelLevel').hidden=o.preset!=='R14';this.$('#wsDimensions').hidden=['aircraft','vehicle'].includes(o.kind);this.$('#wsRadius').hidden=o.kind!=='tank';this.$('#wsThickness').hidden=o.kind!=='wall';this.$('#wsDoor').hidden=o.kind!=='structure'||['CANOPY','PUMP','MANIFOLD','FIRE_EXT','LIGHT_CAM','FLAG_TR','FLAG_AZ','FLAG_SOCAR'].includes(o.preset);for(const [k,v] of Object.entries(values))(form.elements.namedItem(k) as HTMLInputElement).value=v;}
    this.$<HTMLButtonElement>('[data-action="undo"]').disabled=!this.history.past.length;this.$<HTMLButtonElement>('[data-action="redo"]').disabled=!this.history.future.length;
    for(const k of ['duplicate','remove','ground','group','ungroup'])this.$<HTMLButtonElement>(`[data-action="${k}"]`).disabled=!list.length;
  }
  private updateLocation(){if(!this.history)return;this.$('#wsLocation').textContent=this.mode==='airport'?this.l('airport'):this.l('facility');const list=this.selected();this.$('#wsSelection').textContent=list.length===1?list[0].name:list.length?`${list.length} ${this.say('seçili','selected')}`:(this.device.mobile?this.say('Dokun: oraya git · İki parmak: yakınlaş / kaydır','Tap: go there · Two fingers: zoom / pan'):this.say('Tıkla: oraya git · Tekerlek: imlece yakınlaş · Sağ sürükle: kaydır','Click: go there · Wheel: zoom to pointer · Right drag: pan'));}
  private notify(message:string){this.$('#wsToast').textContent=message;this.$('#wsToast').classList.add('show');clearTimeout(this.messageTimer);this.messageTimer=window.setTimeout(()=>this.$('#wsToast').classList.remove('show'),6000);}
  private cancelTool(){this.tool=undefined;this.draft=[];this.$('#wsDrawing').hidden=true;this.stage.classList.remove('placing');this.updateDraft();}
  private updateDraft(){this.plan.draft=this.draft;this.plan.draw();if(this.drawingLine){this.scene.remove(this.drawingLine);this.drawingLine.geometry.dispose();(this.drawingLine.material as THREE.Material).dispose();this.drawingLine=undefined;}if(this.draft.length){this.drawingLine=new THREE.Line(new THREE.BufferGeometry().setFromPoints(this.draft.map(([x,z])=>new THREE.Vector3(x,.2,z))),new THREE.LineBasicMaterial({color:0xb7ff3c}));this.scene.add(this.drawingLine);}this.$('#wsPointCount').textContent=`${this.draft.length} ${this.say('nokta','points')}`;}
  private finishDrawing(){if(!this.tool)return;const c=CATALOG[this.tool],min=c.kind==='ground'?3:2;if(this.draft.length<min){this.notify(this.say(`En az ${min} nokta seçin.`,`Select at least ${min} points.`));return;}const x=this.draft.reduce((s,p)=>s+p[0],0)/this.draft.length,z=this.draft.reduce((s,p)=>s+p[1],0)/this.draft.length,o=newEntity(this.tool,x,z,this.lang);o.points=this.draft.map(p=>[p[0]-x,p[1]-z]);this.change(d=>{numberRefueller(d,o);d.entities.push(o);});this.selection=new Set([o.id]);this.cancelTool();this.refreshSelection();}
  private duplicate(items=this.selected()){if(!this.editing||!items.length)return;const copies=structuredClone(items);copies.forEach(o=>{o.id=id();if(!isRefueller(o.preset))o.name+=this.say(' kopya',' copy');o.position[0]+=3;o.position[2]+=3;o.groupId=undefined;});this.change(d=>{for(const o of copies){numberRefueller(d,o);d.entities.push(o);}});this.selection=new Set(copies.map(o=>o.id));this.refreshSelection();}
  private action(action:string){
    if(this.cabView?.active){if(action==='zoomIn'||action==='zoomOut'){this.cabView.zoom(action==='zoomIn'?-180:180);return;}if(['focus','vehicle','top','free','restoreCamera'].includes(action))this.driving?.setCabin(false);}
    if(['focus','vehicle','top','free','zoomIn','zoomOut','restoreCamera'].includes(action))this.airportOverview=false;
    if(action==='facility-gate'){const gate=this.selected()[0];if(gate&&isFacilityGate(gate)){this.history.change(()=>{gate.gateOpen=!gate.gateOpen;});this.changed();this.updateAnimationButtons();this.notify(gate.gateOpen?this.say('Kapı açık tutulacak.','Gate will stay open.'):this.say('Otomatik kapı: araç tamamen geçince kapanır.','Automatic gate: closes after the complete vehicle clears.'));}return;}
    if(action==='cloud'){this.driving?.pause();this.cloud.open();return;}
    if(action==='drive'){const e=this.selected()[0];if(e&&isRefueller(e.preset)){this.setMenu(undefined);this.driving.open(e);}return;}
    if(action==='night'){this.night=!this.night;this.applyEnvironment();return;}
    if(action==='engine'){const o=this.selected()[0];if(!o||!isRefueller(o.preset))return;this.audio.engine(o.id,!this.running.has(o.id));this.running.has(o.id)?this.running.delete(o.id):this.running.add(o.id);this.updateAnimationButtons();this.plan.draw();return;}
    if(action==='save'){void this.save();return;}if(action==='discard'){void this.requestLeave(true);return;}if(action==='finishEdit'){void this.requestLeave();return;}
    if(action==='free'){if(this.plan.enabled){this.notify(this.say('2D görünümde sürükleyerek serbestçe gezebilirsiniz. 3D’de serbest kamera için 3D’yi açın.','Drag to navigate freely in 2D. Open 3D for the free camera.'));return;}this.setFree(!this.freeMode);return;}
    if(action==='closePanel'){this.$('.ws-panel').hidden=true;this.resize();return;}
    if(action==='library'){this.collapseEditor();this.photo.element.hidden=true;if(this.services.visible)this.services.toggle();this.library.toggle();return;}
    if(action==='zoomIn'||action==='zoomOut'){this.manualCamera();const factor=action==='zoomIn'?.7:1/.7;if(this.plan.enabled)this.plan.zoom(factor);else if(this.freeMode&&this.free){this.flight++;this.free.zoom(action==='zoomIn'?-180:180);}else if(this.orbit){this.flight++;this.camera.position.sub(this.orbit.target).multiplyScalar(factor).add(this.orbit.target);this.orbit.update();this.constrainCamera();this.updateTiles();}return;}
    if(action==='services'){this.collapseEditor();this.library.element.hidden=true;if(!this.photo.element.hidden)this.photo.toggle();this.services.toggle();return;}
    if(action==='photo'){this.collapseEditor();this.library.element.hidden=true;if(this.services.visible)this.services.toggle();this.photo.toggle();return;}
    if(action==='vehicle'){const o=this.history.current.entities.find(o=>isRefueller(o.preset));if(o){this.selection=new Set([o.id]);this.refreshSelection();this.action('focus');}return;}
    if(action==='focus'){this.collapseEditor();const list=this.selected();if(!list.length){this.notify(this.say('Önce haritadan veya nesne listesinden seçim yapın.','Select an object on the map or in the list first.'));return;}const box=new THREE.Box3();list.forEach(o=>{const g=this.objects.get(o.id);if(g)box.expandByObject(g);});const c=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),distance=Math.max(18,Math.max(size.x,size.y,size.z)*2);this.plan.view([c.x,c.z],distance*1.4);this.flyTo(c,distance);return;}
    if(action==='top'){if(this.plan.enabled)return;if(this.freeMode)this.setFree(false);const c=this.orbit!.target.clone(),d=this.camera.position.distanceTo(c);this.flyTo(c,d,true,true);return;}
    if(action==='saveCamera'){try{localStorage.setItem('KS_ADT_ADB_CAMERA',JSON.stringify({position:this.camera.position.toArray(),target:this.orbit?.target.toArray(),center:this.plan.center,span:this.plan.span}));this.notify(this.say('Kamera bu tarayıcıya kaydedildi.','Camera saved in this browser.'));}catch{this.notify(this.say('Kamera kaydedilemedi.','Camera could not be saved.'));}return;}
    if(action==='restoreCamera'){try{const c=JSON.parse(localStorage.getItem('KS_ADT_ADB_CAMERA')||'null');if(!c)throw new Error();this.flight++;this.plan.view(c.center,c.span);if(c.target&&this.orbit){this.camera.position.fromArray(c.position);this.orbit.target.fromArray(c.target);this.orbit.update();this.updateTiles();}}catch{this.notify(this.say('Kayıtlı kamera yok.','No saved camera.'));}return;}
    if(!this.editing)return;
    if(action==='place'){this.collapseEditor();this.cancelTool();this.tool=this.$<HTMLSelectElement>('#wsCatalog').value;this.stage.classList.add('placing');const kind=CATALOG[this.tool].kind;this.$('#wsDrawing').hidden=kind!=='wall'&&kind!=='ground';this.notify(this.say('Yerleştirmek için haritaya tıklayın. Çizimde noktaları seçip Bitir’e basın.','Click the map to place. For a drawing, add points and choose Finish.'));}
    else if(action==='center'){const preset=this.$<HTMLSelectElement>('#wsCatalog').value,c=CATALOG[preset];if(c.kind==='wall'||c.kind==='ground'){this.action('place');return;}const [x,z]=this.plan.enabled?this.plan.center:this.viewCenter();const o=newEntity(preset,x,z,this.lang);this.change(d=>{numberRefueller(d,o);d.entities.push(o);});this.selection=new Set([o.id]);this.refreshSelection();}
    else if(action==='finish')this.finishDrawing();else if(action==='cancel')this.cancelTool();
    else if(action==='undo'||action==='redo'){this.driving?.close();this.cancelTool();if(this.history[action]())this.changed();}
    else if(action==='copy'){this.clipboard=structuredClone(this.selected());this.notify(this.say('Seçim kopyalandı.','Selection copied.'));}else if(action==='paste')this.duplicate(this.clipboard);
    else if(action==='duplicate')this.duplicate();
    else if(action==='remove'){if(this.selection.size)this.change(d=>{d.entities=d.entities.filter(o=>!this.selection.has(o.id));d.groups=d.groups.filter(g=>d.entities.some(o=>o.groupId===g.id));});}
    else if(action==='ground')this.change(d=>d.entities.filter(o=>this.selection.has(o.id)).forEach(o=>o.position[1]=0));
    else if(action==='group'){if(!this.selection.size)return;const name=this.$<HTMLInputElement>('#wsGroupName').value.trim()||this.say('Yeni grup','New group'),gid=id();this.change(d=>{d.groups.push({id:gid,name});d.entities.filter(o=>this.selection.has(o.id)).forEach(o=>o.groupId=gid);d.groups=d.groups.filter(g=>d.entities.some(o=>o.groupId===g.id));});}
    else if(action==='ungroup')this.change(d=>{d.entities.filter(o=>this.selection.has(o.id)).forEach(o=>o.groupId=undefined);d.groups=d.groups.filter(g=>d.entities.some(o=>o.groupId===g.id));});
    else if(action==='export'){this.driving?.pause();const blob=new Blob([JSON.stringify(this.history.current,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`KS-ADB-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
    else if(action==='import'){this.driving?.close();this.$<HTMLInputElement>('#wsImportFile').click();}
  }
  private updateGroundStatus(){const el=this.root.querySelector('#wsMapStatus');if(!el)return;el.textContent=this.groundMode()==='ortho'?(this.staticGround?.failed?this.say('Zemin yüklenemedi; yenilemeyi deneyin.','Ground could not load; try reloading.'):this.staticGround?.ready===2?this.say('Ortak sabit zemin · 3 × 5,1 km','Shared static ground · 3 × 5.1 km'):this.say('Sabit zemin yükleniyor…','Loading static ground…')):this.groundMode()==='photo'?this.say('Referans fotoğraf · yaklaşık hizalama','Reference photo · approximate alignment'):this.say('Zemin planı','Ground plan');}
  private async save(){if(!this.cloud.canEdit){this.unlockDesign();return false;}if(this.saving)return false;this.driving?.pause();this.saving=true;this.updateSaveState();const snapshot=structuredClone(this.history.current);try{const ok=await this.cloud.save(snapshot);if(ok){this.session.commit(snapshot,json=>localStorage.setItem(STORE,json));this.storageWarning=false;this.renderList();}return ok;}catch{this.storageWarning=true;this.notify(this.say('Kayıt yapılamadı. JSON dışarı aktar ile yedekleyin.','Save failed. Export JSON for backup.'));return false;}finally{this.saving=false;this.updateSaveState();}}
  private updateSaveState(){if(!this.session)return;const dirty=this.session.dirty(this.history.current);this.$('.ws-savebar').hidden=!this.cloud?.canEdit||(!this.editing&&!dirty&&!this.cloud?.pending);this.$('#wsSaveState').textContent=(dirty?this.say('● Kaydedilmemiş değişiklikler · ','● Unsaved changes · '):'')+(this.cloud?.status||this.say('Bu cihazda kayıt','Saved on this device'));this.$<HTMLButtonElement>('[data-action="save"]').disabled=!this.cloud?.canEdit||this.saving||this.cloud?.busy||(!dirty&&!this.cloud?.pending);const account=this.$<HTMLButtonElement>('[data-action="cloud"]');account.textContent=this.cloud?.canEdit?this.say('Tasarımcı hesabı','Designer account'):this.say('Gösterim / Tasarımcı girişi','Viewing / Designer sign-in');account.title=this.cloud?.status||'';}
  async requestLeave(discard=false):Promise<boolean>{
    this.driving?.pause();
    if(!this.cloud?.canEdit){this.driving?.close();if(this.session){this.history=new SceneHistory(this.session.discard());this.selection.clear();this.changed();}if(this.editing)this.setEditing(false);return true;}
    if(!this.session||!this.session.dirty(this.history.current)){if(this.editing)this.setEditing(false);return true;}
    if(this.exitDialog)return this.exitDialog;
    this.exitDialog=new Promise(resolve=>{const dialog=document.createElement('dialog');dialog.className='ws-dialog';dialog.innerHTML=`<h2>${this.say('Değişiklikler kaydedilmedi','Changes are not saved')}</h2><p>${this.say('Kaydetmeden çıkarsanız son kayıtlı sahneniz geri gelir.','Discarding restores your last saved scene.')}</p><div><button data-result="save">${this.say('Kaydet ve çık','Save & exit')}</button><button data-result="discard">${this.say('Kaydetmeden çık','Discard & exit')}</button><button data-result="cancel">${this.say('Düzenlemeye devam','Continue editing')}</button></div>`;this.root.appendChild(dialog);const finish=async(value:string)=>{if(value==='save'&&!await this.save())return;if(value==='discard'){this.driving?.close();this.history=new SceneHistory(this.session.discard());this.selection.clear();this.changed();}if(value!=='cancel')this.setEditing(false);dialog.close();dialog.remove();this.exitDialog=undefined;resolve(value!=='cancel');};dialog.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.onclick=()=>finish(b.dataset.result!));dialog.oncancel=e=>{e.preventDefault();finish('cancel');};dialog.showModal();dialog.querySelector<HTMLButtonElement>(`[data-result="${discard?'discard':'save'}"]`)!.focus();});return this.exitDialog;
  }
  private viewCenter():[number,number]{if(this.freeMode){const dir=this.camera.getWorldDirection(new THREE.Vector3());const p=new THREE.Ray(this.camera.position,dir).intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),new THREE.Vector3())||this.camera.position.clone().addScaledVector(dir,40);return [p.x,p.z];}return this.orbit?[this.orbit.target.x,this.orbit.target.z]:[0,0];}
  private setFree(enabled:boolean){this.flight++;this.freeMode=enabled;if(this.free){this.free.enabled=enabled;this.free.paused=false;this.free.clear();this.free.sync();}if(this.orbit){this.orbit.enabled=!enabled;if(!enabled){const v=this.camera.getWorldDirection(new THREE.Vector3());this.orbit.target.copy(this.camera.position).addScaledVector(v,Math.max(5,this.camera.position.y*1.5));this.orbit.target.y=Math.max(0,this.orbit.target.y);this.orbit.update();}}this.$('[data-action="free"]').classList.toggle('active',enabled);this.updatePad();this.notify(enabled?this.say('Serbest kamera: sürükle = bakış · W/A/S/D = ilerle · Q/E = alçal/yüksel · Shift = hızlan.','Free camera: drag = look · W/A/S/D = move · Q/E = lower/rise · Shift = faster.'):this.say('Nesne çevresinde dönme: sol sürükle. Serbest kaydırma: sağ sürükle.','Orbit: left drag. Pan freely: right drag.'));}
  private updatePad(){const moving=this.editing&&this.selection.size>0&&!this.driving?.active;this.$('.ws-move-pad').hidden=!moving&&(!this.freeMode||this.plan.enabled);this.$('#wsPadLabel').textContent=moving?this.say('Seçili nesne · 0,5 m','Selected · 0.5 m'):this.say('Serbest kamera','Free camera');}
  private bindPad(){this.root.querySelectorAll<HTMLButtonElement>('[data-pad]').forEach(b=>{const key=({up:'w',down:'s',left:'a',right:'d',rise:'e',lower:'q'} as Record<string,string>)[b.dataset.pad!];b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(this.editing&&this.selection.size){const d=b.dataset.pad;this.change(scene=>moveEntities(scene,this.selection,d==='left'?-.5:d==='right'?.5:0,d==='up'?-.5:d==='down'?.5:0,d==='rise'?.5:d==='lower'?-.5:0));}else{this.flight++;this.free?.key(key,true);}};b.onpointerup=b.onpointercancel=()=>this.free?.key(key,false);});}
  private bind3DEditing(){
    const canvas=this.inputCanvas!,box=this.$('#wsBoxSelect');let gesture:{pointer:number;start:[number,number];last:THREE.Vector3;box:boolean;extend:boolean;moved:boolean;hit?:string}|undefined;
    const ray=(e:PointerEvent)=>{const r=canvas.getBoundingClientRect(),v=new THREE.Raycaster();v.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2),this.camera);return v;};
    const floor=(e:PointerEvent)=>ray(e).ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),new THREE.Vector3());
    canvas.addEventListener('pointerdown',e=>{this.flight++;if(this.free)this.free.paused=false;if(!this.editing||this.driving?.active||this.tool||e.button!==0||e.pointerType==='touch'||this.transform?.axis)return;let hit=ray(e).intersectObjects([...this.objects.values()],true)[0]?.object;while(hit&&!hit.userData.entityId)hit=hit.parent!;const p=floor(e);if(!e.shiftKey&&(!hit||!this.selection.has(hit.userData.entityId)||e.ctrlKey||e.metaKey))return;if(!p)return;gesture={pointer:e.pointerId,start:[e.clientX,e.clientY],last:p,hit:hit?.userData.entityId,box:e.shiftKey,extend:e.ctrlKey||e.metaKey,moved:false};canvas.setPointerCapture(e.pointerId);if(this.orbit)this.orbit.enabled=false;if(this.free)this.free.paused=true;e.stopImmediatePropagation();},true);
    canvas.addEventListener('pointermove',e=>{const g=gesture;if(!g||e.pointerId!==g.pointer)return;e.stopImmediatePropagation();if(!g.moved&&Math.hypot(e.clientX-g.start[0],e.clientY-g.start[1])<5)return;if(!g.moved&&!g.box)this.history.checkpoint();g.moved=true;if(g.box){const r=canvas.getBoundingClientRect();box.hidden=false;Object.assign(box.style,{left:`${Math.min(e.clientX,g.start[0])-r.left}px`,top:`${Math.min(e.clientY,g.start[1])-r.top}px`,width:`${Math.abs(e.clientX-g.start[0])}px`,height:`${Math.abs(e.clientY-g.start[1])}px`});}else{const p=floor(e);if(p){moveEntities(this.history.current,this.selection,p.x-g.last.x,p.z-g.last.z);g.last.copy(p);this.syncObjects();}}},true);
    const up=(e:PointerEvent)=>{const g=gesture;if(!g)return;e.stopImmediatePropagation();gesture=undefined;box.hidden=true;if(this.orbit)this.orbit.enabled=!this.freeMode;if(this.free)this.free.paused=false;if(g.box&&g.moved&&e.type!=='pointercancel'){if(!g.extend)this.selection.clear();const r=canvas.getBoundingClientRect();for(const o of this.history.current.entities){const v=new THREE.Vector3().fromArray(o.position).project(this.camera),x=r.left+(v.x+1)*r.width/2,y=r.top+(1-v.y)*r.height/2;if(v.z>=-1&&v.z<=1&&x>=Math.min(g.start[0],e.clientX)&&x<=Math.max(g.start[0],e.clientX)&&y>=Math.min(g.start[1],e.clientY)&&y<=Math.max(g.start[1],e.clientY))this.selection.add(o.id);}this.refreshSelection();}else if(g.moved)this.changed();else if(e.type!=='pointercancel')this.clickMap(0,0,g.hit,g.extend);};canvas.addEventListener('pointerup',up,true);canvas.addEventListener('pointercancel',up,true);
  }
  private tintGround(){this.groundScene.traverse(n=>{if(n instanceof THREE.Mesh&&n.material instanceof THREE.MeshBasicMaterial&&n.renderOrder<1100){const m=n.material;const base=m.userData.dayColor??(m.userData.dayColor=m.color.clone());m.color.copy(base);if(this.night)m.color.multiply(new THREE.Color(.18,.24,.36));}});}
  private applyEnvironment(){this.root.dataset.lighting=this.night?'night':'day';this.plan.night=this.night;this.skyLight.intensity=this.night?.38:2.5;this.sunLight.intensity=this.night?.12:3;const sky=this.night?'#07111e':'#94adb7';this.renderer?.setClearColor(sky);(this.scene.fog as THREE.Fog).color.set(sky);this.tintGround();this.plan.draw();this.updateAnimationButtons();}
  private updateAnimationButtons(){if(!this.history)return;const night=this.$<HTMLButtonElement>('[data-action="night"]');night.textContent=this.night?this.say('Gündüz modu','Day mode'):this.say('Gece modu','Night mode');night.setAttribute('aria-pressed',String(this.night));night.classList.toggle('active',this.night);const engine=this.$<HTMLButtonElement>('[data-action="engine"]'),running=this.selected().length===1&&this.running.has(this.selected()[0].id);engine.textContent=running?this.say('Aracı durdur','Stop vehicle'):this.say('Aracı çalıştır','Start vehicle');engine.setAttribute('aria-pressed',String(running));engine.classList.toggle('active',running);const o=this.selected().length===1?this.selected()[0]:undefined,pack=o?this.mixers.get(o.id):undefined;this.$('.ws-animations').hidden=!o||!isRefueller(o.preset);this.$('.ws-gate-controls').hidden=!o||!isFacilityGate(o);this.$('[data-action="facility-gate"]').textContent=o?.gateOpen?this.say('Kapıyı otomatiğe al','Set gate to automatic'):this.say('Tesis kapısını aç','Open facility gate');const names:Record<string,string>={Platform_Raise_4s:this.say('Platform','Platform'),Tank_Railing_Raise:this.say('Tank korkuluğu','Tank railing'),Platform_Gate_Open:this.say('Platform kapısı','Platform gate')};this.root.querySelectorAll<HTMLButtonElement>('[data-animation]').forEach(b=>{const clip=b.dataset.animation!;b.disabled=!pack?.actions.has(clip);b.setAttribute('aria-pressed',String(!!pack?.open.has(clip)));b.textContent=`${names[clip]} · ${pack?.open.has(clip)?this.say('Kapat','Close'):this.say('Aç','Open')}`;});}
  private animate(clip:string){if(this.driving?.motion&&Math.abs(this.driving.motion.speed)>.01){this.notify(this.say('Önce aracı durdurun.','Stop the vehicle first.'));return;}const o=this.selected()[0];if(!o)return;const pack=this.mixers.get(o.id),a=pack?.actions.get(clip);if(!a||!pack)return;const opening=!pack.open.has(clip);a.enabled=true;a.paused=false;a.setLoop(THREE.LoopOnce,1);a.clampWhenFinished=true;a.timeScale=opening?1:-1;if(opening&&a.time>=a.getClip().duration-.01)a.time=0;if(!opening&&a.time<=.01)a.time=a.getClip().duration;a.play();opening?pack.open.add(clip):pack.open.delete(clip);this.updateAnimationButtons();}
}
