import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { TransformControls } from 'three/examples/jsm/controls/TransformControls.js';
import { GLTFLoader, type GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { clone as cloneModel } from 'three/examples/jsm/utils/SkeletonUtils.js';
import { makeObject, applyTransform, disposeObject } from './objects';
import { CATALOG, SceneHistory, importScene, validateScene, newEntity, moveEntities, id, type Entity } from './scene-data';
import { Imagery, MapPlane, PlanMap } from './maps';
import { AIRPORT_CENTER, FACILITY_CENTER, geographic } from './geo';
import './workspace.css';
type Lang='tr'|'en';
const STORE='KS_DIGITAL_TWIN_ADB_V1';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const labels:Record<string,[string,string]>={world:['Dünya','World'],turkey:['Türkiye','Türkiye'],airport:['ADB Havalimanı','ADB Airport'],facility:['ADB Tesisi','ADB Facility'],design:['Çizim / Tasarım','Draw / Design'],inspect:['İncele','Inspect'],objects:['Nesneler ve gruplar','Objects and groups'],add:['Nesne ekle / çiz','Add / draw'],place:['Haritada yerleştir','Place on map'],center:['Merkeze ekle','Add at center'],finish:['Çizimi bitir','Finish drawing'],cancel:['Vazgeç','Cancel'],satellite:['Uydu haritası','Satellite map'],top:['Üstten bak','Top view'],focus:['Seçilene git','Focus selected'],vehicle:['R14 araca git','Focus R14'],translate:['Taşı (W)','Move (W)'],rotate:['Döndür (E)','Rotate (E)'],scale:['Ölçekle (R)','Scale (R)'],undo:['Geri al','Undo'],redo:['İleri al','Redo'],duplicate:['Çoğalt','Duplicate'],remove:['Sil','Delete'],ground:['Zemine oturt','Ground'],group:['Grupla','Group'],ungroup:['Grubu çöz','Ungroup'],export:['JSON dışarı aktar','Export JSON'],import:['JSON içeri al','Import JSON'],name:['Nesne adı','Object name'],heading:['Yön (°)','Heading (°)'],size:['Ölçek','Scale'],height:['Yükseklik (m)','Elevation (m)'],color:['Renk','Color'],apply:['Değişiklikleri uygula','Apply changes'],selected:['Seçili nesne','Selected object'],search:['Nesne ara…','Search objects…'],groupName:['Grup adı','Group name'],saveCamera:['Kamerayı kaydet','Save camera'],restoreCamera:['Kayıtlı kamera','Saved camera']};
export class Workspace {
  history!:SceneHistory;selection=new Set<string>();editing=false;mode:'airport'|'facility'='facility';
  private scene=new THREE.Scene();private camera=new THREE.PerspectiveCamera(42,1,.1,30000);private renderer?:THREE.WebGLRenderer;private orbit?:OrbitControls;private transform?:TransformControls;
  private pivot=new THREE.Group();private objects=new Map<string,THREE.Group>();private fingerprints=new Map<string,string>();private selectionBox=new THREE.Box3Helper(new THREE.Box3(),0xb7ff3c);
  private imagery=new Imagery();private plane=new MapPlane(this.imagery);private plan!:PlanMap;private stage!:HTMLElement;
  private active=true;private tool:string|undefined;private draft:[number,number][]=[];private drawingLine?:THREE.Line;
  private drag=false;private transformStart:{base:THREE.Vector3;entities:Entity[]} |undefined;
  private modelPromise?:Promise<GLTF>;private mixers=new Map<string,{mixer:THREE.AnimationMixer;actions:Map<string,THREE.AnimationAction>;open:Set<string>}>();
  private flight=0;private storageWarning=false;private messageTimer=0;private dragStart?:[number,number];private clipboard:Entity[]=[];
  private l=(key:string)=>labels[key]?.[this.lang==='tr'?0:1]||key;
  private say=(tr:string,en:string)=>this.lang==='tr'?tr:en;
  constructor(private root:HTMLElement,private lang:Lang,private exit:(where:'world'|'turkey')=>void){}
  async init(){
    this.root.innerHTML=`<div class="ws-nav"><div class="ws-crumb"><span class="ws-dot"></span><strong>ADB / LTBJ</strong><small id="wsSource"></small></div><div class="ws-tabs">${['world','turkey','airport','facility','design'].map(k=>`<button data-nav="${k}" data-label="${k}"></button>`).join('')}</div></div>
    <div class="ws-body"><aside class="ws-panel" hidden><div class="ws-section"><h3 data-label="add"></h3><select id="wsCatalog" aria-label="Nesne türü">${Object.entries(CATALOG).map(([k,v])=>`<option value="${k}">${this.lang==='tr'?v.tr:v.en}</option>`).join('')}</select><div class="ws-row"><button data-action="place" data-label="place"></button><button data-action="center" data-label="center"></button></div><div id="wsDrawing" hidden><button data-action="finish" data-label="finish"></button><button data-action="cancel" data-label="cancel"></button><small id="wsPointCount"></small></div></div>
    <div class="ws-section"><div class="ws-row ws-triple">${['translate','rotate','scale'].map(k=>`<button data-transform="${k}" data-label="${k}"></button>`).join('')}</div><div class="ws-row">${['undo','redo','duplicate','remove','ground'].map(k=>`<button data-action="${k}" data-label="${k}"></button>`).join('')}</div><div class="ws-nudge"><button data-nudge="0,-.5" aria-label="Kuzeye 0,5 m">↑</button><button data-nudge="-.5,0" aria-label="Batıya 0,5 m">←</button><span>0,5 m</span><button data-nudge=".5,0" aria-label="Doğuya 0,5 m">→</button><button data-nudge="0,.5" aria-label="Güneye 0,5 m">↓</button><button data-turn="-5" aria-label="Sola 5 derece">↶ 5°</button><button data-turn="5" aria-label="Sağa 5 derece">5° ↷</button></div></div>
    <details class="ws-section" open><summary data-label="selected"></summary><div id="wsEmpty"></div><form id="wsProperties" hidden><label><span data-label="name"></span><input name="name" maxlength="100"></label><div class="ws-row"><label>X (m)<input name="x" type="number" step="0.01" required></label><label>Z (m)<input name="z" type="number" step="0.01" required></label></div><div class="ws-row"><label><span data-label="height"></span><input name="y" type="number" step="0.01" min="0" required></label><label><span data-label="heading"></span><input name="heading" type="number" step="0.1" required></label><label><span data-label="size"></span><input name="scale" type="number" step="0.01" min="0.02" max="100" required></label><label><span data-label="color"></span><input name="color" type="color"></label></div><button type="submit" class="ws-primary" data-label="apply"></button></form></details>
    <div class="ws-section"><h3 data-label="objects"></h3><input id="wsSearch" aria-label="Nesne ara"><div id="wsObjectList"></div><input id="wsGroupName" maxlength="80"><div class="ws-row"><button data-action="group" data-label="group"></button><button data-action="ungroup" data-label="ungroup"></button></div></div><div class="ws-section ws-row"><button data-action="export" data-label="export"></button><button data-action="import" data-label="import"></button></div></aside>
    <div class="ws-map"><div class="ws-toolbar"><button data-view="3d">3D</button><button data-view="2d">2D</button><button data-action="top" data-label="top"></button><button data-action="focus" data-label="focus"></button><button data-action="vehicle" data-label="vehicle"></button><label class="ws-check"><input type="checkbox" id="wsSatellite" checked><span data-label="satellite"></span></label><button data-action="saveCamera" data-label="saveCamera"></button><button data-action="restoreCamera" data-label="restoreCamera"></button></div><div id="wsStage" tabindex="0"></div><div id="wsFallback" hidden></div><div id="wsToast" role="status" aria-live="polite"></div><div class="ws-hud"><strong id="wsLocation"></strong><span id="wsSelection"></span><small id="wsMapStatus"></small></div><div class="ws-animations" hidden><button data-animation="Platform_Raise_4s"></button><button data-animation="Tank_Railing_Raise"></button><button data-animation="Platform_Gate_Open"></button></div><div class="ws-credit">Tiles © Esri · Vantor · Earthstar Geographics · GIS User Community <a href="https://goto.arcgisonline.com/maps/World_Imagery" target="_blank" rel="noopener">Sources</a></div></div></div><input id="wsImportFile" type="file" accept=".json,application/json" hidden>`;
    const response=await fetch('/data/adb-legacy.json');if(!response.ok)throw new Error('ADB verisi alınamadı.');const source=importScene(await response.json());
    let data=source;try{const raw=localStorage.getItem(STORE);if(raw)data=validateScene(JSON.parse(raw));}catch{this.storageWarning=true;}
    if(data===source){const [x,z]=[16,20];const truck=newEntity('R14',x,z,this.lang);truck.heading=165;data.entities.push(truck);}
    this.history=new SceneHistory(data);this.stage=this.$('#wsStage');
    this.scene.background=new THREE.Color('#94adb7');this.scene.fog=new THREE.Fog('#94adb7',7000,25000);this.scene.add(this.plane.group,this.pivot,this.selectionBox);this.selectionBox.visible=false;
    this.scene.add(new THREE.HemisphereLight(0xe9f7ff,0x596552,2.5));const light=new THREE.DirectionalLight(0xfff6e9,3);light.position.set(-120,240,90);this.scene.add(light);
    const ground=new THREE.Mesh(new THREE.PlaneGeometry(60000,60000),new THREE.MeshStandardMaterial({color:'#56695c',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.1;this.scene.add(ground);
    this.plan=new PlanMap(this.stage,this.imagery,{entities:()=>this.history.current.entities,selection:()=>this.selection,editable:()=>this.editing,drawing:()=>!!this.tool,click:(x,z,hit,extend)=>this.clickMap(x,z,hit,extend),dragStart:()=>this.history.checkpoint(),drag:(dx,dz)=>{moveEntities(this.history.current,this.selection,dx,dz);this.syncObjects();},dragEnd:()=>this.changed(),change:()=>this.updateLocation()});
    try{
      this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;this.renderer.domElement.className='world-canvas';this.renderer.domElement.setAttribute('aria-label','ADB 3D sahne');this.stage.appendChild(this.renderer.domElement);
      this.orbit=new OrbitControls(this.camera,this.renderer.domElement);this.orbit.enableDamping=true;this.orbit.maxPolarAngle=Math.PI/2-.025;this.orbit.minDistance=4;this.orbit.maxDistance=17000;this.orbit.screenSpacePanning=false;
      this.orbit.addEventListener('start',()=>{this.flight++;});this.orbit.addEventListener('end',()=>{this.updateTiles();this.updateLocation();});
      this.transform=new TransformControls(this.camera,this.renderer.domElement);this.transform.setSize(.8);this.transform.showY=false;this.scene.add(this.transform.getHelper());this.transform.enabled=false;
      this.transform.addEventListener('mouseDown',()=>this.beginTransform());this.transform.addEventListener('objectChange',()=>this.applyGizmo());this.transform.addEventListener('mouseUp',()=>{if(this.drag){this.drag=false;if(this.orbit)this.orbit.enabled=true;this.changed();}});
      this.renderer.domElement.addEventListener('pointerdown',e=>{this.dragStart=[e.clientX,e.clientY];});
      this.renderer.domElement.addEventListener('pointerup',e=>{if(e.button!==0||this.transform?.axis||!this.dragStart||Math.hypot(e.clientX-this.dragStart[0],e.clientY-this.dragStart[1])>4)return;const r=this.renderer!.domElement.getBoundingClientRect();const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2),this.camera);const p=ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),new THREE.Vector3());if(!p)return;let hit:THREE.Object3D|undefined=ray.intersectObjects([...this.objects.values()],true)[0]?.object;while(hit&&!hit.userData.entityId)hit=hit.parent||undefined;this.clickMap(p.x,p.z,hit?.userData.entityId,e.shiftKey);});
      this.setView('3d');
    }catch(e){console.warn('ADB 2D fallback',e);this.renderer=undefined;this.setView('2d');this.$<HTMLButtonElement>('[data-view="3d"]').disabled=true;this.$('#wsFallback').hidden=false;}
    this.imagery.onChange=()=>{this.plane.sync();this.plan.draw();const ready=this.imagery.active.filter(t=>t.ready).length,failed=this.imagery.active.filter(t=>t.failed).length;this.$('#wsMapStatus').textContent=this.imagery.enabled?(failed===this.imagery.active.length&&failed>0?this.say('Uydu bağlantısı yok · zemin planı açık','Imagery unavailable · plan visible'):`${this.say('Uydu','Imagery')} ${ready}/${this.imagery.active.length}`):this.say('Zemin planı','Ground plan');};
    this.bind();this.setLanguage(this.lang);this.syncObjects();this.navigate('facility',false);new ResizeObserver(()=>this.resize()).observe(this.stage);this.resize();
    const clock=new THREE.Clock();const frame=()=>{requestAnimationFrame(frame);const dt=Math.min(.05,clock.getDelta());if(!this.active||document.hidden)return;for(const {mixer} of this.mixers.values())mixer.update(dt);if(!this.plan.enabled&&this.renderer){this.orbit?.update();this.updateSelectionBox();this.renderer.render(this.scene,this.camera);}};frame();
    if(this.storageWarning)this.notify(this.say('Yerel kayıt okunamadı; kaynak sahne açıldı.','Local save could not be read; source scene opened.'));
  }
  private $<T extends HTMLElement=HTMLElement>(s:string){return this.root.querySelector<T>(s)!;}
  private bind(){
    this.root.querySelectorAll<HTMLButtonElement>('[data-nav]').forEach(b=>b.onclick=()=>{const n=b.dataset.nav!;if(n==='world'||n==='turkey'){this.exit(n);return;}if(n==='design')this.setEditing(!this.editing);else{this.navigate(n as 'airport'|'facility');}});
    this.root.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.onclick=()=>this.setView(b.dataset.view as '2d'|'3d'));
    this.root.querySelectorAll<HTMLButtonElement>('[data-transform]').forEach(b=>b.onclick=()=>this.setTransform(b.dataset.transform as 'translate'|'rotate'|'scale'));
    this.root.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(b=>b.onclick=()=>this.action(b.dataset.action!));
    this.root.querySelectorAll<HTMLButtonElement>('[data-nudge]').forEach(b=>b.onclick=()=>{if(!this.editing||!this.selection.size)return;const [x,z]=b.dataset.nudge!.split(',').map(Number);this.change(d=>moveEntities(d,this.selection,x,z));});
    this.root.querySelectorAll<HTMLButtonElement>('[data-turn]').forEach(b=>b.onclick=()=>{if(this.editing)this.change(d=>d.entities.filter(o=>this.selection.has(o.id)).forEach(o=>o.heading+=Number(b.dataset.turn)));});
    this.root.querySelectorAll<HTMLButtonElement>('[data-animation]').forEach(b=>b.onclick=()=>this.animate(b.dataset.animation!));
    this.$<HTMLInputElement>('#wsSatellite').onchange=()=>{this.imagery.enabled=this.$<HTMLInputElement>('#wsSatellite').checked;this.updateTiles();this.plan.refresh();};
    this.$<HTMLInputElement>('#wsSearch').oninput=()=>this.renderList();
    this.$<HTMLFormElement>('#wsProperties').onsubmit=e=>{e.preventDefault();if(!this.editing||this.selection.size!==1)return;const f=new FormData(this.$<HTMLFormElement>('#wsProperties'));const values=['x','y','z','heading','scale'].map(k=>Number(f.get(k)));if(values.some(n=>!Number.isFinite(n))||values.slice(0,3).some(n=>Math.abs(n)>50000))return;this.change(d=>{const o=d.entities.find(o=>this.selection.has(o.id))!;o.name=String(f.get('name')).slice(0,100);o.position=[values[0],Math.max(0,values[1]),values[2]];o.heading=values[3];o.scale=Math.max(.02,Math.min(100,values[4]));o.color=String(f.get('color'));});};
    this.$<HTMLInputElement>('#wsImportFile').onchange=async()=>{const input=this.$<HTMLInputElement>('#wsImportFile'),file=input.files?.[0];if(!file)return;try{if(file.size>12_000_000)throw new Error(this.say('Dosya en fazla 12 MB olabilir.','File must be under 12 MB.'));const data=importScene(JSON.parse(await file.text()));this.history.checkpoint();this.history.current=data;this.selection.clear();this.changed();this.notify(this.say(`${data.entities.length} nesne içe alındı. Geri Al ile önceki sahneye dönebilirsin.`,`${data.entities.length} objects imported. Undo restores the previous scene.`));}catch(e){this.notify(String(e));}input.value='';};
    window.addEventListener('keydown',e=>{if(!this.active||!this.editing||(e.target as HTMLElement).closest('input,textarea,select,[contenteditable]'))return;const mod=e.ctrlKey||e.metaKey,k=e.key.toLowerCase();if(mod&&k==='z'){e.preventDefault();this.action(e.shiftKey?'redo':'undo');}else if(mod&&k==='y'){e.preventDefault();this.action('redo');}else if(mod&&k==='c'){e.preventDefault();this.clipboard=this.selected().map(o=>structuredClone(o));}else if(mod&&k==='v'){e.preventDefault();this.duplicate(this.clipboard);}else if(k==='delete'||k==='backspace'){e.preventDefault();this.action('remove');}else if(k==='escape')this.action('cancel');else if(k==='enter'&&this.tool)this.action('finish');else if(!mod&&['w','e','r'].includes(k))this.setTransform(({w:'translate',e:'rotate',r:'scale'} as const)[k as 'w']);});
  }
  setLanguage(lang:Lang){this.lang=lang;this.root.querySelectorAll<HTMLElement>('[data-label]').forEach(e=>e.textContent=this.l(e.dataset.label!));this.$<HTMLInputElement>('#wsSearch').placeholder=this.l('search');this.$<HTMLInputElement>('#wsGroupName').placeholder=this.l('groupName');this.$<HTMLSelectElement>('#wsCatalog').querySelectorAll('option').forEach(o=>o.textContent=lang==='tr'?CATALOG[o.value].tr:CATALOG[o.value].en);this.$('#wsFallback').textContent=this.say('WebGL kullanılamıyor. 2D harita ve tasarım araçları açık.','WebGL unavailable. 2D map and design tools are available.');this.renderList();this.renderProperties();this.updateLocation();this.updateAnimationButtons();}
  show(mode:'airport'|'facility',edit=false){this.active=true;this.root.hidden=false;this.navigate(mode);this.setEditing(edit);requestAnimationFrame(()=>this.resize());}
  hide(){this.active=false;this.root.hidden=true;this.flight++;}
  navigate(mode:'airport'|'facility',smooth=true){this.mode=mode;const c=mode==='airport'?AIRPORT_CENTER:FACILITY_CENTER;const distance=mode==='airport'?4600:130;this.plan.view(c,mode==='airport'?6200:185);this.flyTo(new THREE.Vector3(c[0],0,c[1]),distance,smooth);this.root.querySelectorAll<HTMLElement>('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===mode||(b.dataset.nav==='design'&&this.editing)));this.updateLocation();}
  setEditing(enabled:boolean){this.editing=enabled;this.$('.ws-panel').hidden=!enabled;this.root.classList.toggle('editing',enabled);this.$('[data-nav="design"]').classList.toggle('active',enabled);this.cancelTool();this.updateSelectionBox();this.renderProperties();this.resize();}
  private setView(view:'2d'|'3d'){
    if(view==='3d'&&!this.renderer)return;const was2d=this.plan.enabled;this.plan.enabled=view==='2d';this.plan.canvas.hidden=!this.plan.enabled;if(this.renderer)this.renderer.domElement.hidden=this.plan.enabled;
    if(this.plan.enabled&&this.orbit&&!was2d){this.plan.center=[this.orbit.target.x,this.orbit.target.z];this.plan.span=Math.max(30,this.camera.position.distanceTo(this.orbit.target)*1.4);}
    if(!this.plan.enabled&&was2d)this.flyTo(new THREE.Vector3(this.plan.center[0],0,this.plan.center[1]),this.plan.span/1.4,false);
    this.root.querySelectorAll<HTMLElement>('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));this.updateSelectionBox();this.plan.refresh();this.resize();
  }
  private resize(){const w=this.stage.clientWidth,h=this.stage.clientHeight;if(w&&h&&this.renderer){this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false);}this.plan.draw();}
  private updateTiles(){if(this.plan.enabled){this.imagery.update(...this.plan.center,this.plan.span);return;}if(this.orbit)this.imagery.update(this.orbit.target.x,this.orbit.target.z,this.camera.position.distanceTo(this.orbit.target)*1.5);}
  private flyTo(target:THREE.Vector3,distance:number,smooth=true,top=false){
    if(!this.orbit)return;const start=this.camera.position.clone(),startTarget=this.orbit.target.clone(),end=target.clone().add(top?new THREE.Vector3(0,distance,.001):new THREE.Vector3(distance*.64,distance*.65,distance*.52));const token=++this.flight,t=performance.now();
    const step=(now:number)=>{if(token!==this.flight)return;const k=smooth?Math.min(1,(now-t)/850):1,q=1-(1-k)**3;this.camera.position.lerpVectors(start,end,q);this.orbit!.target.lerpVectors(startTarget,target,q);this.orbit!.update();if(k<1)requestAnimationFrame(step);else this.updateTiles();};requestAnimationFrame(step);
  }
  private clickMap(x:number,z:number,hit:string|undefined,extend:boolean){
    if(this.tool&&this.editing){const c=CATALOG[this.tool];if(c.kind==='ground'||c.kind==='wall'){this.draft.push([x,z]);this.updateDraft();if(this.tool==='MAIN_GATE'&&this.draft.length===2)this.finishDrawing();}else{const o=newEntity(this.tool,x,z,this.lang);this.change(d=>d.entities.push(o));this.selection=new Set([o.id]);this.cancelTool();this.refreshSelection();}return;}
    if(!extend)this.selection.clear();if(hit){if(extend&&this.selection.has(hit))this.selection.delete(hit);else this.selection.add(hit);}this.refreshSelection();
  }
  private selected(){return this.history.current.entities.filter(o=>this.selection.has(o.id));}
  private change(fn:(d:SceneHistory['current'])=>void){if(!this.editing)return;this.history.change(fn);this.changed();}
  private changed(){this.history.current.updatedAt=new Date().toISOString();try{localStorage.setItem(STORE,JSON.stringify(this.history.current));this.storageWarning=false;}catch{this.storageWarning=true;this.notify(this.say('Tarayıcı kaydı yapılamadı. JSON dışarı aktar ile yedekle.','Browser save failed. Export JSON to keep a backup.'));}this.syncObjects();this.renderList();this.renderProperties();this.updateLocation();}
  private syncObjects(){
    const ids=new Set(this.history.current.entities.map(o=>o.id));
    for(const [key,g] of this.objects)if(!ids.has(key)){this.scene.remove(g);disposeObject(g);this.objects.delete(key);this.fingerprints.delete(key);this.mixers.delete(key);this.selection.delete(key);}
    for(const o of this.history.current.entities){const fingerprint=JSON.stringify([o.kind,o.preset,o.color,o.width,o.length,o.height,o.radius,o.thickness,o.points,o.wallStyle,o.flag,o.doorSide]);let g=this.objects.get(o.id);
      if(!g||this.fingerprints.get(o.id)!==fingerprint){if(g){this.scene.remove(g);disposeObject(g);this.mixers.delete(o.id);}g=makeObject(o);this.scene.add(g);this.objects.set(o.id,g);this.fingerprints.set(o.id,fingerprint);if(o.preset==='R14')void this.loadR14(o,g);}
      applyTransform(g,o);
    }
    this.updateSelectionBox();this.plan.draw();
  }
  private async loadR14(o:Entity,root:THREE.Group){
    try{
      this.modelPromise??=new GLTFLoader().loadAsync('/models/refueller-38k-r14.glb');const gltf=await this.modelPromise;if(this.objects.get(o.id)!==root)return;
      const model=cloneModel(gltf.scene),bounds=new THREE.Box3().setFromObject(model),size=bounds.getSize(new THREE.Vector3()),center=bounds.getCenter(new THREE.Vector3()),s=o.length/Math.max(size.x,size.z);
      // Ground and center the asset inside a stable selectable wrapper.
      model.scale.setScalar(s);model.position.set(-center.x*s,-bounds.min.y*s,-center.z*s);
      const orient=new THREE.Group();orient.add(model);if(size.x>size.z)orient.rotation.y=Math.PI/2;
      disposeObject(root);root.clear();root.add(orient);root.userData.modelPending=false;model.traverse(n=>{if(n instanceof THREE.Mesh)n.userData.sharedAsset=true;});
      const mixer=new THREE.AnimationMixer(model),actions=new Map<string,THREE.AnimationAction>();gltf.animations.forEach(c=>actions.set(c.name,mixer.clipAction(c)));this.mixers.set(o.id,{mixer,actions,open:new Set()});this.updateSelectionBox();this.updateAnimationButtons();
    }catch(e){this.modelPromise=undefined;root.userData.modelError=true;this.notify(this.say('R14 modeli yüklenemedi. Bağlantıyı kontrol ederek sayfayı yenileyin.','R14 could not load. Check your connection and reload.'));console.warn(e);}
  }
  private refreshSelection(){this.updateSelectionBox();this.renderList();this.renderProperties();this.updateLocation();this.updateAnimationButtons();this.plan.draw();}
  private updateSelectionBox(){
    const list=this.selected();this.selectionBox.visible=list.length>0&&!this.plan.enabled;this.selectionBox.box.makeEmpty();for(const o of list){const g=this.objects.get(o.id);if(g){g.updateMatrixWorld(true);this.selectionBox.box.union(new THREE.Box3().setFromObject(g));}}
    if(this.transform&&!this.drag){if(this.editing&&list.length&&!this.plan.enabled){const center=new THREE.Vector3();list.forEach(o=>center.add(new THREE.Vector3().fromArray(o.position)));center.divideScalar(list.length);this.pivot.position.copy(center);this.pivot.rotation.set(0,0,0);this.pivot.scale.setScalar(1);this.transform.attach(this.pivot);this.transform.enabled=true;}else{this.transform.detach();this.transform.enabled=false;}}
  }
  private setTransform(mode:'translate'|'rotate'|'scale'){if(this.transform){this.transform.setMode(mode);this.transform.showX=mode!=='rotate';this.transform.showY=mode==='rotate';this.transform.showZ=mode!=='rotate';}this.root.querySelectorAll<HTMLElement>('[data-transform]').forEach(b=>b.classList.toggle('active',b.dataset.transform===mode));}
  private beginTransform(){if(!this.editing)return;this.drag=true;this.flight++;if(this.orbit)this.orbit.enabled=false;this.history.checkpoint();this.transformStart={base:this.pivot.position.clone(),entities:structuredClone(this.selected())};}
  private applyGizmo(){
    if(!this.drag||!this.transformStart)return;const {base,entities}=this.transformStart,delta=this.pivot.position.clone().sub(base),rot=this.pivot.rotation.y,factor=Math.max(.02,this.pivot.scale.x!==1?this.pivot.scale.x:this.pivot.scale.z),c=Math.cos(rot),s=Math.sin(rot);
    for(const original of entities){const o=this.history.current.entities.find(o=>o.id===original.id)!;const x=(original.position[0]-base.x)*factor,z=(original.position[2]-base.z)*factor;o.position=[base.x+c*x+s*z+delta.x,Math.max(0,base.y+(original.position[1]-base.y)*factor+delta.y),base.z-s*x+c*z+delta.z];o.heading=original.heading-THREE.MathUtils.radToDeg(rot);o.scale=Math.max(.02,Math.min(100,original.scale*factor));}
    this.syncObjects();
  }
  private renderList(){
    if(!this.history)return;const q=this.$<HTMLInputElement>('#wsSearch').value.toLocaleLowerCase(),data=this.history.current;const openGroups=new Set(Array.from(this.$('#wsObjectList').querySelectorAll<HTMLElement>('details[open]')).map(e=>e.dataset.groupSection));
    const row=(o:Entity)=>`<button class="ws-object ${this.selection.has(o.id)?'selected':''}" data-object="${esc(o.id)}"><i style="background:${o.color}"></i><span>${esc(o.name)}</span><small>${o.preset}</small></button>`;
    const match=(o:Entity)=>!q||`${o.name} ${o.preset}`.toLocaleLowerCase().includes(q);
    this.$('#wsObjectList').innerHTML=data.groups.map(g=>{const objs=data.entities.filter(o=>o.groupId===g.id&&match(o));if(!objs.length)return '';return `<details data-group-section="${esc(g.id)}" ${q||openGroups.has(g.id)||objs.some(o=>this.selection.has(o.id))?'open':''}><summary><button data-group="${esc(g.id)}">${esc(g.name)} <small>${objs.length}</small></button></summary>${objs.map(row).join('')}</details>`;}).join('')+data.entities.filter(o=>(!o.groupId||!data.groups.some(g=>g.id===o.groupId))&&match(o)).map(row).join('');
    this.$('#wsObjectList').querySelectorAll<HTMLButtonElement>('[data-object]').forEach(b=>b.onclick=e=>{this.cancelTool();this.clickMap(0,0,b.dataset.object,(e as MouseEvent).shiftKey);});
    this.$('#wsObjectList').querySelectorAll<HTMLButtonElement>('[data-group]').forEach(b=>b.onclick=e=>{e.preventDefault();this.cancelTool();if(!(e as MouseEvent).shiftKey)this.selection.clear();data.entities.filter(o=>o.groupId===b.dataset.group).forEach(o=>this.selection.add(o.id));this.refreshSelection();});
    this.$('#wsSource').title=data.source;this.$('#wsSource').textContent=`${data.entities.length} ${this.say('nesne','objects')} · ${this.storageWarning?this.say('Kayıt uyarısı','Save warning'):this.say('Bu tarayıcıya otomatik kayıt','Autosaved in this browser')}`;
  }
  private renderProperties(){
    if(!this.history)return;const list=this.selected(),form=this.$<HTMLFormElement>('#wsProperties');form.hidden=list.length!==1;this.$('#wsEmpty').hidden=list.length===1;this.$('#wsEmpty').textContent=list.length?this.say(`${list.length} nesne seçili. Taşıma ve gruplama birlikte uygulanır.`,`${list.length} objects selected. Move and group them together.`):this.say('Haritadan veya listeden bir nesne seçin.','Select an object on the map or in the list.');
    if(list.length===1){const o=list[0];const values={name:o.name,x:o.position[0].toFixed(2),y:o.position[1].toFixed(2),z:o.position[2].toFixed(2),heading:o.heading.toFixed(1),scale:o.scale.toFixed(2),color:o.color};for(const [k,v] of Object.entries(values))(form.elements.namedItem(k) as HTMLInputElement).value=v;}
    this.$<HTMLButtonElement>('[data-action="undo"]').disabled=!this.history.past.length;this.$<HTMLButtonElement>('[data-action="redo"]').disabled=!this.history.future.length;
    for(const k of ['duplicate','remove','ground','group','ungroup'])this.$<HTMLButtonElement>(`[data-action="${k}"]`).disabled=!list.length;
  }
  private updateLocation(){if(!this.history)return;this.$('#wsLocation').textContent=this.mode==='airport'?this.l('airport'):this.l('facility');const list=this.selected();this.$('#wsSelection').textContent=list.length===1?list[0].name:list.length?`${list.length} ${this.say('seçili','selected')}`:this.say('Sürükle: kamera · Tekerlek: yakınlaş · Shift+tık: çoklu seçim','Drag: camera · Wheel: zoom · Shift+click: multi-select');}
  private notify(message:string){this.$('#wsToast').textContent=message;this.$('#wsToast').classList.add('show');clearTimeout(this.messageTimer);this.messageTimer=window.setTimeout(()=>this.$('#wsToast').classList.remove('show'),6000);}
  private cancelTool(){this.tool=undefined;this.draft=[];this.$('#wsDrawing').hidden=true;this.stage.classList.remove('placing');this.updateDraft();}
  private updateDraft(){this.plan.draft=this.draft;this.plan.draw();if(this.drawingLine){this.scene.remove(this.drawingLine);this.drawingLine.geometry.dispose();(this.drawingLine.material as THREE.Material).dispose();this.drawingLine=undefined;}if(this.draft.length){this.drawingLine=new THREE.Line(new THREE.BufferGeometry().setFromPoints(this.draft.map(([x,z])=>new THREE.Vector3(x,.2,z))),new THREE.LineBasicMaterial({color:0xb7ff3c}));this.scene.add(this.drawingLine);}this.$('#wsPointCount').textContent=`${this.draft.length} ${this.say('nokta','points')}`;}
  private finishDrawing(){if(!this.tool)return;const c=CATALOG[this.tool],min=c.kind==='ground'?3:2;if(this.draft.length<min){this.notify(this.say(`En az ${min} nokta seçin.`,`Select at least ${min} points.`));return;}const x=this.draft.reduce((s,p)=>s+p[0],0)/this.draft.length,z=this.draft.reduce((s,p)=>s+p[1],0)/this.draft.length,o=newEntity(this.tool,x,z,this.lang);o.points=this.draft.map(p=>[p[0]-x,p[1]-z]);this.change(d=>d.entities.push(o));this.selection=new Set([o.id]);this.cancelTool();this.refreshSelection();}
  private duplicate(items=this.selected()){if(!this.editing||!items.length)return;const copies=structuredClone(items);copies.forEach(o=>{o.id=id();o.name+=this.say(' kopya',' copy');o.position[0]+=3;o.position[2]+=3;o.groupId=undefined;});this.change(d=>d.entities.push(...copies));this.selection=new Set(copies.map(o=>o.id));this.refreshSelection();}
  private action(action:string){
    if(action==='vehicle'){const o=this.history.current.entities.find(o=>o.preset==='R14');if(o){this.selection=new Set([o.id]);this.refreshSelection();this.action('focus');}return;}
    if(action==='focus'){const list=this.selected();if(!list.length)return;const box=new THREE.Box3();list.forEach(o=>{const g=this.objects.get(o.id);if(g)box.expandByObject(g);});const c=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),distance=Math.max(18,Math.max(size.x,size.y,size.z)*2);this.plan.view([c.x,c.z],distance*1.4);this.flyTo(c,distance);return;}
    if(action==='top'){if(this.plan.enabled)return;const c=this.orbit!.target.clone(),d=this.camera.position.distanceTo(c);this.flyTo(c,d,true,true);return;}
    if(action==='saveCamera'){try{localStorage.setItem('KS_ADT_ADB_CAMERA',JSON.stringify({position:this.camera.position.toArray(),target:this.orbit?.target.toArray(),center:this.plan.center,span:this.plan.span}));this.notify(this.say('Kamera bu tarayıcıya kaydedildi.','Camera saved in this browser.'));}catch{this.notify(this.say('Kamera kaydedilemedi.','Camera could not be saved.'));}return;}
    if(action==='restoreCamera'){try{const c=JSON.parse(localStorage.getItem('KS_ADT_ADB_CAMERA')||'null');if(!c)throw new Error();this.flight++;this.plan.view(c.center,c.span);if(c.target&&this.orbit){this.camera.position.fromArray(c.position);this.orbit.target.fromArray(c.target);this.orbit.update();this.updateTiles();}}catch{this.notify(this.say('Kayıtlı kamera yok.','No saved camera.'));}return;}
    if(!this.editing)return;
    if(action==='place'){this.cancelTool();this.tool=this.$<HTMLSelectElement>('#wsCatalog').value;this.stage.classList.add('placing');const kind=CATALOG[this.tool].kind;this.$('#wsDrawing').hidden=kind!=='wall'&&kind!=='ground';this.notify(this.say('Yerleştirmek için haritaya tıklayın. Çizimde noktaları seçip Bitir’e basın.','Click the map to place. For a drawing, add points and choose Finish.'));}
    else if(action==='center'){const preset=this.$<HTMLSelectElement>('#wsCatalog').value,c=CATALOG[preset];if(c.kind==='wall'||c.kind==='ground'){this.action('place');return;}const [x,z]=this.plan.enabled?this.plan.center:[this.orbit!.target.x,this.orbit!.target.z];const o=newEntity(preset,x,z,this.lang);this.change(d=>d.entities.push(o));this.selection=new Set([o.id]);this.refreshSelection();}
    else if(action==='finish')this.finishDrawing();else if(action==='cancel')this.cancelTool();
    else if(action==='undo'||action==='redo'){this.cancelTool();if(this.history[action]())this.changed();}
    else if(action==='duplicate')this.duplicate();
    else if(action==='remove'){if(this.selection.size)this.change(d=>{d.entities=d.entities.filter(o=>!this.selection.has(o.id));d.groups=d.groups.filter(g=>d.entities.some(o=>o.groupId===g.id));});}
    else if(action==='ground')this.change(d=>d.entities.filter(o=>this.selection.has(o.id)).forEach(o=>o.position[1]=0));
    else if(action==='group'){if(!this.selection.size)return;const name=this.$<HTMLInputElement>('#wsGroupName').value.trim()||this.say('Yeni grup','New group'),gid=id();this.change(d=>{d.groups.push({id:gid,name});d.entities.filter(o=>this.selection.has(o.id)).forEach(o=>o.groupId=gid);d.groups=d.groups.filter(g=>d.entities.some(o=>o.groupId===g.id));});}
    else if(action==='ungroup')this.change(d=>{d.entities.filter(o=>this.selection.has(o.id)).forEach(o=>o.groupId=undefined);d.groups=d.groups.filter(g=>d.entities.some(o=>o.groupId===g.id));});
    else if(action==='export'){const blob=new Blob([JSON.stringify(this.history.current,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`KS-ADB-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
    else if(action==='import')this.$<HTMLInputElement>('#wsImportFile').click();
  }
  private updateAnimationButtons(){if(!this.history)return;const o=this.selected().length===1?this.selected()[0]:undefined,pack=o?this.mixers.get(o.id):undefined;this.$('.ws-animations').hidden=o?.preset!=='R14';const names:Record<string,string>={Platform_Raise_4s:this.say('Platform','Platform'),Tank_Railing_Raise:this.say('Tank korkuluğu','Tank railing'),Platform_Gate_Open:this.say('Platform kapısı','Platform gate')};this.root.querySelectorAll<HTMLButtonElement>('[data-animation]').forEach(b=>{const clip=b.dataset.animation!;b.disabled=!pack?.actions.has(clip);b.textContent=`${names[clip]} ${pack?.open.has(clip)?'↓':'↑'}`;});}
  private animate(clip:string){const o=this.selected()[0];if(!o)return;const pack=this.mixers.get(o.id),a=pack?.actions.get(clip);if(!a||!pack)return;const opening=!pack.open.has(clip);a.enabled=true;a.paused=false;a.setLoop(THREE.LoopOnce,1);a.clampWhenFinished=true;a.timeScale=opening?1:-1;if(opening&&a.time>=a.getClip().duration-.01)a.time=0;if(!opening&&a.time<=.01)a.time=a.getClip().duration;a.play();opening?pack.open.add(clip):pack.open.delete(clip);this.updateAnimationButtons();}
}
